#!/usr/bin/env python3
"""Assemble the Claude skill bundle(s) for the `agent-governance` plugin from the catalogue sources.

A Claude plugin is copied to a local cache on install and cannot reach files outside its own directory,
so each skill must vendor everything it references. This script is the single writer of the generated
half of the plugin, and it is **registry-driven**: each `SkillSpec` in `SPECS` declares what one skill
needs, and the same machinery bundles every spec — so adding a skill is "add a `SkillSpec`," not a fork.

For a skill that mirrors the catalogue (e.g. `self-governance`), it copies the requested roles' entries
into `reference/`, emits a scoped `INDEX.md`, vendors any referenced download templates, and lifts Part A
of a starter governance doc into `principles.md`. A skill with no mirror (`include_roles=()`) gets just
its `principles.md` — its own reference material ships in the authored `SKILL.md` half.

It is the skill analogue of `catalog.py build`: the bundles are GENERATED, never hand-edited, so they
can't drift from the catalogue. Runs on every commit via `hooks/pre-commit`. Stdlib-only; imports
`catalog` for the shared entry model.

Exit codes (per the repo's subprocess convention): 0 = success, 1 = failure.
"""
from __future__ import annotations

import glob
import os
import re
import shutil
import sys
from typing import NamedTuple

import catalog  # shared Entry model + ROOT; import-safe (main() is __main__-guarded)

ROOT = catalog.ROOT
PLUGIN_SKILLS = os.path.join(ROOT, "plugin", "agent-governance", "skills")  # the umbrella plugin's skills dir
PUBLIC = "https://davisjam.github.io/agent-governance-mechanisms/"  # base for links that leave the bundle

GEN_NOTE = "<!-- GENERATED by bundle_skill.py from the catalogue sources — do not hand-edit; edits are overwritten on the next build. -->\n"


class SkillSpec(NamedTuple):
    """One skill's bundle recipe. Adding a skill = adding a `SkillSpec` to `SPECS` below."""
    name: str                 # the skill dir name under the plugin's skills/
    starter_doc: str          # abs path to the Part-A source doc (its Part A → principles.md)
    include_roles: tuple      # catalogue roles mirrored into reference/ ; () = no mirror
    principles_intro: str     # preamble prepended to the lifted Part A in principles.md
    vendor_downloads: tuple = ()  # downloads/ templates shipped in <skill>/templates/ — explicit, so a
    #                               skill with no bundled entries (no reference-based vendoring) still gets them

    @property
    def skill_dir(self) -> str:
        return os.path.join(PLUGIN_SKILLS, self.name)

    @property
    def ref_dir(self) -> str:
        return os.path.join(self.skill_dir, "reference")


# ── The skill registry ─────────────────────────────────────────────────────────────────────────────
SELF_GOVERNANCE = SkillSpec(
    name="self-governance",
    starter_doc=os.path.join(ROOT, "downloads", "CLAUDE-starter.md"),
    include_roles=("agent", "models-bridge"),  # product/ excluded: it governs the artifact, not the self
    principles_intro=(
        GEN_NOTE
        + "<!-- Source: Part A of the project's starter governance doc (a portable mirror of a "
        "mature CLAUDE.md). The copyright / attribution header below is retained verbatim. -->\n\n"
        "# Operating principles — the Davis AI-First Engineering Method\n\n"
        "*These portable principles are the operating stance of the `self-governance` skill. "
        "The catalogue in `reference/` is the set of concrete controls; these principles are the "
        "reasoning that decides when to reach for one.*\n\n---\n\n"
    ),
    # The model-based-software-engineering starter kit: fill-in scaffolds for authoring the 4+1
    # model views (the catalogue documents them as mechanisms; these let a fresh project BUILD them).
    vendor_downloads=(
        "system-models-starter-kit.md",
        "state-machine-model-starter.py",
        "component-zone-model-starter.py",
        "service-flow-model-starter.yaml",
        "service-flow-loader-starter.py",
        "deployment-topology-starter.py",
    ),
)

SELF_OPERATIONS = SkillSpec(
    name="self-operations",
    starter_doc=os.path.join(ROOT, "downloads", "self-operations-starter.md"),
    include_roles=(),  # no catalogue mirror — its reference is the authored SKILL.md map + examples/
    principles_intro=(
        GEN_NOTE
        + "<!-- Source: Part A of the self-operations starter (the portable operating mindset). -->\n\n"
        "# Operating principles — the self-operations mindset\n\n"
        "*The operating stance of the `self-operations` skill: how to run an agent-fleet substrate as a "
        "DevOps engineer. The skill's `SKILL.md` carries the lifecycle map and the bootstrap; these "
        "principles are the mindset you operate with. Partner to the `self-governance` skill.*\n\n---\n\n"
    ),
    # The operate skill authors design docs + Epics (infra changes, the feature-dev flow) — ship the
    # templates locally so it never has to reach outside its own dir (self-governance already vendors
    # these via its reference/downloads/ mirror).
    vendor_downloads=(
        "EPIC-TEMPLATE-starter.md",
        "design-doc-template-starter.md",
        "emit-handoff-starter.py",  # machine-generate the reconstructable handoff sections (L2 banking).
    ),
)

SPECS = [SELF_GOVERNANCE, SELF_OPERATIONS]


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _write_copy(src: str, dst: str) -> None:
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)


def _mirror_entries(spec: SkillSpec) -> int:
    """Copy each included role's entries + role README verbatim into reference/."""
    for role in spec.include_roles:
        dst = os.path.join(spec.ref_dir, role)
        if os.path.isdir(dst):
            shutil.rmtree(dst)
    n = 0
    for e in catalog.all_entries():
        role = e.path.split(os.sep)[0]
        if role not in spec.include_roles:
            continue
        dst = os.path.join(spec.ref_dir, e.path)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(os.path.join(ROOT, e.path), dst)
        n += 1
    for role in spec.include_roles:  # role READMEs aren't entries but ground the family structure
        src = os.path.join(ROOT, role, "README.md")
        if os.path.isfile(src):
            shutil.copyfile(src, os.path.join(spec.ref_dir, role, "README.md"))
    shutil.copyfile(os.path.join(ROOT, "ABSTRACTIONS.md"), os.path.join(spec.ref_dir, "ABSTRACTIONS.md"))
    return n


def _filtered_index(spec: SkillSpec) -> None:
    """Emit reference/INDEX.md = the census truncated to the included roles."""
    full = open(os.path.join(ROOT, "INDEX.md"), encoding="utf-8").read()
    cut = full.find("# Product target")  # everything above product is agent + models-bridge
    body = full[:cut].rstrip() if cut != -1 else full.rstrip()
    # the source line says "All 53 entries…" (full catalogue); this bundle ships only agent+bridge, so
    # rewrite the count to the bundled total to avoid a 53-vs-33 confusion for a fresh reader.
    n_bundled = sum(1 for e in catalog.all_entries() if e.path.split(os.sep)[0] in spec.include_roles)
    body = re.sub(r"All \d+ entries are fully\s+written[^.]*\.",
                  f"All {n_bundled} bundled entries are fully written "
                  "(the product role's entries live in the full catalogue).", body)
    header = (
        GEN_NOTE
        + "<!-- Scope: the agent + models-bridge roles only. The product role is "
        "excluded from this skill; see the full catalogue for it. -->\n\n"
    )
    _write(os.path.join(spec.ref_dir, "INDEX.md"), header + body + "\n")


def _principles(spec: SkillSpec) -> None:
    """Lift Part A (the portable method) out of the skill's starter doc into principles.md."""
    txt = open(spec.starter_doc, encoding="utf-8").read()
    a = txt.find("# Part A")
    b = txt.find("# Part B")
    if a == -1 or b == -1:
        raise SystemExit(f"bundle_skill: could not locate Part A / Part B markers in {spec.starter_doc}")
    part_a = txt[a:b].rstrip().rstrip("-").rstrip()  # drop the trailing '---' separator
    _write(os.path.join(spec.skill_dir, "principles.md"), spec.principles_intro + part_a + "\n")


def _reference_readme(spec: SkillSpec, n: int) -> None:
    _write(
        os.path.join(spec.ref_dir, "README.md"),
        GEN_NOTE
        + "\n# Reference catalogue (bundled)\n\n"
        f"A vendored copy of the **agent** and **models-bridge** roles of the "
        f"agent-governance-mechanisms catalogue ({n} mechanism entries), assembled by "
        "`bundle_skill.py` so the skill is self-contained when installed. Start at "
        "[`INDEX.md`](INDEX.md); read individual entries on demand. Canonical source + the "
        "product role: https://davisjam.github.io/agent-governance-mechanisms/\n",
    )


def _vendor_referenced_downloads(spec: SkillSpec) -> int:
    """Copy any downloads/ template a BUNDLED entry references into reference/downloads/, so the
    'Adopt it ->' handoff links resolve when the skill is installed (the plugin cache can't reach
    outside its own dir). Only templates referenced by the bundled entries are vendored. The relative
    depth matches: `../../downloads/X` from `reference/<role>/<family>/<control>.md` lands in
    reference/downloads/."""
    dst_dir = os.path.join(spec.ref_dir, "downloads")
    if os.path.isdir(dst_dir):
        shutil.rmtree(dst_dir)  # regenerate fresh so a de-referenced template doesn't linger
    referenced: set[str] = set()
    for f in glob.glob(os.path.join(spec.ref_dir, "**", "*.md"), recursive=True):
        with open(f, encoding="utf-8") as fh:
            referenced.update(re.findall(r"\]\([^)]*downloads/([^)\s#]+)\)", fh.read()))
    n = 0
    for name in sorted(referenced):
        src = os.path.join(ROOT, "downloads", name)
        if os.path.isfile(src):
            _write_copy(src, os.path.join(dst_dir, name))
            n += 1
    return n


def _vendor_explicit_downloads(spec: SkillSpec) -> int:
    """Copy each template named in spec.vendor_downloads into <skill>/templates/ — explicit templates a
    skill ships regardless of what its (possibly empty) bundled entry set references. Regenerated fresh so
    a de-listed template doesn't linger."""
    if not spec.vendor_downloads:
        return 0
    dst_dir = os.path.join(spec.skill_dir, "templates")
    if os.path.isdir(dst_dir):
        shutil.rmtree(dst_dir)
    n = 0
    for name in spec.vendor_downloads:
        src = os.path.join(ROOT, "downloads", name)
        if os.path.isfile(src):
            _write_copy(src, os.path.join(dst_dir, name))
            n += 1
    return n


def _rewrite_outbound_links(spec: SkillSpec) -> None:
    """Repoint links that leave the bundle so none dangles once installed: excluded-product cross-refs
    -> the live public product pages; source-project-internal `docs/` pointers -> plain text (no public
    target). Intra-bundle links (other entries, vendored downloads) are left untouched."""
    targets = glob.glob(os.path.join(spec.ref_dir, "**", "*.md"), recursive=True) + [os.path.join(spec.skill_dir, "principles.md")]
    for f in targets:
        if not os.path.isfile(f):
            continue
        txt = open(f, encoding="utf-8").read()
        txt = re.sub(r"\]\((?:\.\./)+product/([^)\s#]+)\.md\)", lambda m: f"]({PUBLIC}product/{m.group(1)}.html)", txt)
        txt = re.sub(r"\]\((?:\.\./)+product/\)", f"]({PUBLIC}product/)", txt)
        txt = re.sub(r"\[([^\]]*)\]\(docs/[^)]+\)", r"\1", txt)  # unpublished treatise -> keep text, drop the link
        with open(f, "w", encoding="utf-8") as fh:
            fh.write(txt)


def _bundle(spec: SkillSpec) -> None:
    """Run the full pipeline for one skill. Mirror steps run only when the spec includes roles."""
    print(f"== bundle-skill: {spec.name} ==")
    n = 0
    if spec.include_roles:
        print(f"  roles: {', '.join(spec.include_roles)} (product excluded)")
        n = _mirror_entries(spec)
        _filtered_index(spec)
    _principles(spec)
    d = 0
    if spec.include_roles:
        _reference_readme(spec, n)
        d = _vendor_referenced_downloads(spec)
    _rewrite_outbound_links(spec)
    v = _vendor_explicit_downloads(spec)
    extra = f" + {v} vendored template(s)" if v else ""
    print(f"  -> {os.path.relpath(spec.skill_dir, ROOT)}/ : {n} mechanism entries + principles.md + {d} referenced download(s){extra}")


def main() -> int:
    for spec in SPECS:
        _bundle(spec)
    return 0


if __name__ == "__main__":
    sys.exit(main())
