#!/usr/bin/env python3
"""Assemble the `self-governance` Claude skill bundle from the catalogue sources.

A Claude plugin is copied to a local cache on install and cannot reach files outside
its own directory, so the skill must vendor everything it references. This script is
the single writer of the generated half of the plugin — it mirrors the catalogue's
`agent/` + `models-bridge/` entries (the two governance targets that make up "the
self"; `product/` is deliberately excluded) into the skill's `reference/`, and lifts
Part A of the redacted starter governance doc into `principles.md`.

It is the skill's analogue of `catalog.py build`: the bundle is GENERATED, never
hand-edited, so it can't drift from the catalogue. Runs on every commit via
`hooks/pre-commit`. Stdlib-only; imports `catalog` for the shared entry model.

Exit codes (per the repo's subprocess convention): 0 = success, 1 = failure.
"""
from __future__ import annotations

import os
import shutil
import sys

import catalog  # shared Entry model + ROOT; import-safe (main() is __main__-guarded)

ROOT = catalog.ROOT
INCLUDE_ROLES = ("agent", "models-bridge")  # product/ excluded: it governs the artifact, not the self
SKILL = os.path.join(ROOT, "plugin", "self-governance", "skills", "self-governance")
REF = os.path.join(SKILL, "reference")
STARTER = os.path.join(ROOT, "downloads", "CLAUDE-starter.md")

GEN_NOTE = "<!-- GENERATED by bundle_skill.py from the catalogue sources — do not hand-edit; edits are overwritten on the next build. -->\n"


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _mirror_entries() -> int:
    """Copy each included role's entries + role README verbatim into reference/."""
    for role in INCLUDE_ROLES:
        dst = os.path.join(REF, role)
        if os.path.isdir(dst):
            shutil.rmtree(dst)
    n = 0
    for e in catalog.all_entries():
        role = e.path.split(os.sep)[0]
        if role not in INCLUDE_ROLES:
            continue
        dst = os.path.join(REF, e.path)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(os.path.join(ROOT, e.path), dst)
        n += 1
    for role in INCLUDE_ROLES:  # role READMEs aren't entries but ground the family structure
        src = os.path.join(ROOT, role, "README.md")
        if os.path.isfile(src):
            shutil.copyfile(src, os.path.join(REF, role, "README.md"))
    shutil.copyfile(os.path.join(ROOT, "ABSTRACTIONS.md"), os.path.join(REF, "ABSTRACTIONS.md"))
    return n


def _filtered_index() -> None:
    """Emit reference/INDEX.md = the census truncated to the included roles."""
    full = open(os.path.join(ROOT, "INDEX.md"), encoding="utf-8").read()
    cut = full.find("# Product target")  # everything above product is agent + models-bridge
    body = full[:cut].rstrip() if cut != -1 else full.rstrip()
    header = (
        GEN_NOTE
        + "<!-- Scope: the agent + models-bridge roles only. The product role is "
        "excluded from this skill; see the full catalogue for it. -->\n\n"
    )
    _write(os.path.join(REF, "INDEX.md"), header + body + "\n")


def _principles() -> None:
    """Lift Part A (the portable method) out of the redacted starter governance doc."""
    txt = open(STARTER, encoding="utf-8").read()
    a = txt.find("# Part A")
    b = txt.find("# Part B")
    if a == -1 or b == -1:
        raise SystemExit("bundle_skill: could not locate Part A / Part B markers in the starter doc")
    part_a = txt[a:b].rstrip().rstrip("-").rstrip()  # drop the trailing '---' separator
    intro = (
        GEN_NOTE
        + "<!-- Source: downloads/CLAUDE-starter.md (Part A), itself a redacted mirror of a "
        "mature CLAUDE.md. The copyright / attribution header below is retained verbatim. -->\n\n"
        "# Operating principles — the Davis AI-First Engineering Method\n\n"
        "*These portable principles are the operating stance of the `self-governance` skill. "
        "The catalogue in `reference/` is the set of concrete controls; these principles are the "
        "reasoning that decides when to reach for one.*\n\n---\n\n"
    )
    _write(os.path.join(SKILL, "principles.md"), intro + part_a + "\n")


def _reference_readme(n: int) -> None:
    _write(
        os.path.join(REF, "README.md"),
        GEN_NOTE
        + "\n# Reference catalogue (bundled)\n\n"
        f"A vendored copy of the **agent** and **models-bridge** roles of the "
        f"agent-governance-mechanisms catalogue ({n} control entries), assembled by "
        "`bundle_skill.py` so the skill is self-contained when installed. Start at "
        "[`INDEX.md`](INDEX.md); read individual entries on demand. Canonical source + the "
        "product role: https://davisjam.github.io/agent-governance-mechanisms/\n",
    )


def main() -> int:
    print("== bundle-skill plan ==")
    print(f"  roles: {', '.join(INCLUDE_ROLES)} (product excluded)")
    print(f"  -> {os.path.relpath(REF, ROOT)}/ + principles.md")
    n = _mirror_entries()
    _filtered_index()
    _principles()
    _reference_readme(n)
    print(f"bundled {n} control entries + INDEX + ABSTRACTIONS + principles.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
