"""The ARGUMENT-SPINE view — a typed model of the book's linear argument: an ordered run of numbered
claims, plus a labeling of every chapter by the spine claim(s) it advances. The sixth sibling model beside
outline / outcomes / concepts / big-ideas / claims (directive book/_design/book-editorial-discipline-directive-260802.md
Part A Task 1 / Part B Phase 1).

WHY A NEW MODEL, NOT AN EXTENSION.  The claims model holds unordered stances, each with the contradiction
predicate an audit checks prose against. The Big-Ideas model holds six fixed landing slots. A spine claim
is neither: it is an ordered STEP in the argument the book makes from front to back, and its distinctive
fields — `order`, seed provenance, reconciliation links, chapter advancement — belong to no sibling. The
same rule that earned the claims model its own file (a new field none of the siblings carry) applies here.

RECONCILE, DON'T RESTATE.  The spine is not a second source for the siblings' content. Each spine claim
carries `reconciles` links: the claim ids (claims_declared.json) and big-idea slugs (landing-big-ideas.json)
it subsumes into one argument step, plus the author's seed-statement numbers it descends from. The
structural check holds the reconciliation COMPLETE in both directions: every link resolves (AS3), and every
sibling claim id and big-idea slug is reconciled by some spine claim (AS4) — so a stance added to a sibling
model without a place in the argument is a finding, not a silent orphan.

CHAPTER LABELS LIVE HERE, NOT IN THE OUTLINE.  The outline model is derived from the book on every run —
it has no hand-authored source a judgment field could live in — and the outcomes model is pedagogical. The
per-chapter advancement judgment is argument-structural, so it homes here: `chapter_advances` maps every
outline chapter slug to the spine ids it advances, and the generated artifact projects the reverse
(`advanced_by`, per spine claim). Exhaustiveness over the outline's chapters is invariant AS5.

FOCUS FLAGS ARE DERIVED, INFORMATIONAL, AND NEVER GATE.  The directive's two editorial smells — a chapter
advancing 0 spine claims (suspect: why does it exist?) and a MIDDLE chapter advancing more than
FOCUS_CAP (probably unfocused) — are computed by the generator into the artifact's `flags` block. Chapters
whose breadth or silence is their job carry a `chapter_exemptions` reason from the closed EXEMPT_REASONS
enum (preface / conclusion / discussion / end-of-part-synthesis / apparatus / overview). The flags are the
orchestrator's refactor worklist (Phase 1c of the directive); they are surfaced, never a gate finding.

Run `python3 book-models/argument_spine_model.py regenerate` to write the artifact; `... verify` to
drift-check; `... spine` to print the argument; `... flags` to print the focus worklist.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import outline_model as om  # noqa: E402 — the outline view is the chapter tree the labels map onto

_HERE = os.path.dirname(os.path.abspath(__file__))
_ARTIFACT = os.path.join(_HERE, "argument-spine.json")
_DECLARED = os.path.join(_HERE, "argument_spine_declared.json")

_PROVENANCE = ("GENERATED by book-models/argument_spine_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/argument_spine_model.py regenerate`. Derived from the hand-authored "
               "spine + chapter labels in book-models/argument_spine_declared.json, resolved against the "
               "outline + the claims + big-ideas sibling models.")

_MODEL_NOTE = (
    "The argument-spine model holds the book's linear argument as an ordered run of claims, each "
    "reconciling the author's seed statements, the claims model, and the Big-Ideas model into one step — "
    "plus the per-chapter labeling of which steps each chapter advances. The `flags` block is DERIVED "
    "editorial signal (a non-exempt chapter advancing 0 steps is suspect; one advancing more than the "
    "focus cap is probably unfocused); it is the refactor worklist for the directive's Phase 1c and never "
    "gates. Exempt chapters (preface / conclusion / discussion / end-of-part synthesis / apparatus) are "
    "the ones whose breadth or silence is their job.")

#: The `statement` word cap — a spine claim is one argument step, not a paragraph. Counted with
#: `statement.split()`, mirroring the claims model's C6. Higher than the claims model's 18 because a spine
#: step often joins a cause to its consequence in one sentence.
WORD_CAP = 26

#: The spine's size bounds — the directive asks for the argument in ~10–20 numbered statements (AS2).
SPINE_MIN, SPINE_MAX = 10, 20

#: A non-exempt chapter advancing more than this many spine claims is flagged probably-unfocused (the
#: directive's editorial smell). Breadth beyond the cap is only appropriate for the exempt kinds.
FOCUS_CAP = 3

#: The CLOSED reasons a chapter may be exempt from the focus flags (AS7). `apparatus` covers
#: non-argumentative front/back matter (acknowledgments); `overview` covers a deliberate whole-book
#: survey chapter — a reason the orchestrator ratifies before it is used.
EXEMPT_REASONS = ("preface", "conclusion", "discussion", "end-of-part-synthesis", "apparatus", "overview")

#: The author's 10 seed statements (directive Part A Task 1) — the valid `seeds` numbers (AS2).
SEED_MIN, SEED_MAX = 1, 10


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class SpineClaim:
    """One ordered step of the book's argument. `id` is the kebab join key; `order` its 1-based position;
    `seeds` the author seed-statement numbers it descends from; `reconciles_claims` / `reconciles_big_ideas`
    the sibling-model entries it subsumes. `advanced_by` is DERIVED — the chapters labeled with this step."""
    id: str
    order: int
    statement: str
    seeds: list[int]
    reconciles_claims: list[str]
    reconciles_big_ideas: list[str]
    word_count: int = 0                              # derived: statement.split() length
    advanced_by: list[str] = field(default_factory=list)  # derived: chapter slugs that advance this step


@dataclass
class ChapterLabel:
    """One chapter's argument label: the spine ids it advances, and its exemption (or None)."""
    slug: str
    advances: list[str]
    exempt: "str | None"


@dataclass
class SpineModel:
    spine: list[SpineClaim]
    chapters: list[ChapterLabel]

    def flags(self) -> "dict[str, list[dict]]":
        """The DERIVED focus flags — the directive's two editorial smells over the non-exempt chapters."""
        zero = [{"chapter": c.slug, "advances": 0}
                for c in self.chapters if not c.exempt and not c.advances]
        over = [{"chapter": c.slug, "advances": len(c.advances), "spine_ids": list(c.advances)}
                for c in self.chapters if not c.exempt and len(c.advances) > FOCUS_CAP]
        return {"zero_claim_suspects": zero, "over_cap_unfocused": over}


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model() -> SpineModel:
    """Build the spine model from the hand-authored declarations — the single derivation the regen and the
    drift check share. Spine order is the argument's own order; chapters follow the outline's order, so the
    artifact is deterministic."""
    decl = _load_declared()
    spine = [SpineClaim(
        id=d["id"], order=d["order"], statement=d["statement"],
        seeds=list(d.get("seeds", [])),
        reconciles_claims=list(d.get("reconciles", {}).get("claims", [])),
        reconciles_big_ideas=list(d.get("reconciles", {}).get("big_ideas", [])),
        word_count=len(d["statement"].split()),
    ) for d in decl["spine"]]
    spine.sort(key=lambda s: s.order)

    advances: "dict[str, list[str]]" = decl.get("chapter_advances", {})
    exemptions: "dict[str, str]" = decl.get("chapter_exemptions", {})
    outline = om.derive_outline()
    chapters = [ChapterLabel(slug=c.slug, advances=list(advances.get(c.slug, [])),
                             exempt=exemptions.get(c.slug))
                for c in outline.chapters]
    # Any label keyed to a chapter the outline no longer defines still surfaces (AS5 reddens it), appended
    # after the outline's chapters so the artifact never silently drops a hand-authored label.
    known = {c.slug for c in outline.chapters}
    for slug in advances:
        if slug not in known:
            chapters.append(ChapterLabel(slug=slug, advances=list(advances[slug]),
                                         exempt=exemptions.get(slug)))

    # Derive the reverse projection: spine claim -> chapters that advance it.
    by_id = {s.id: s for s in spine}
    for ch in chapters:
        for sid in ch.advances:
            if sid in by_id:
                by_id[sid].advanced_by.append(ch.slug)
    return SpineModel(spine=spine, chapters=chapters)


# ---- sibling-model key sets -------------------------------------------------------------------------

def _load_json(path: str) -> "dict | None":
    return json.load(open(path, encoding="utf-8")) if os.path.isfile(path) else None


def _sibling_sets() -> "tuple[set[str], set[str]]":
    """(claim_ids, big_idea_slugs) — the resolve targets for `reconciles` (AS3/AS4), read at check time
    from the sibling declared sources; a single source of truth, no snapshot."""
    claims = _load_json(os.path.join(_HERE, "claims_declared.json")) or {}
    claim_ids = {c["id"] for c in claims.get("claims", [])}
    big = _load_json(os.path.join(_HERE, "landing-big-ideas.json")) or {}
    # The argument ideas are the `_order` six; the file also carries non-argument slots (the catalogue
    # gateway), which are not reconciliation targets.
    idea_slugs = set(big.get("_order", [])) or {k for k in big if not k.startswith("_")}
    return claim_ids, idea_slugs


# ---- invariants (AS1–AS7; walked by the drift check in tests/book_models.py) -------------------------

def structural_findings(model: "SpineModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants. Deterministic; the focus flags are NOT findings (they are the
    artifact's `flags` block — editorial signal, not schema violation).

    AS2 — spine ids unique + kebab; `order` is exactly 1..N contiguous; N within [SPINE_MIN, SPINE_MAX];
          every `seeds` number within the author's 1..10 seed set; statement within WORD_CAP.
    AS3 — every `reconciles` link resolves: claim ids against claims_declared.json, big-idea slugs against
          landing-big-ideas.json.
    AS4 — the reconciliation is COMPLETE: every sibling claim id and every big-idea slug is reconciled by
          ≥1 spine claim (a sibling stance with no place in the argument is a finding).
    AS5 — `chapter_advances` keys are exactly the outline's chapter slugs (exhaustive labeling; a label
          keyed to a chapter the book no longer defines reddens too).
    AS6 — every advanced id names a spine claim; no duplicate ids within one chapter's label.
    AS7 — every exemption reason ∈ EXEMPT_REASONS; every exemption key is a labeled chapter.

    (AS1, drift — the artifact equals a fresh derivation — is walked by the tests/book_models.py check and
    the `verify` CLI, mirroring the siblings.)"""
    if model is None:
        model = derive_model()
    claim_ids, idea_slugs = _sibling_sets()
    findings: "list[str]" = []

    # AS2 — id + order + seed + word-cap shape.
    seen: "set[str]" = set()
    for s in model.spine:
        if s.id in seen:
            findings.append(f"AS2 duplicate spine id {s.id!r}")
        seen.add(s.id)
        if not all(part.isalnum() for part in s.id.split("-")) or s.id != s.id.lower():
            findings.append(f"AS2 spine id {s.id!r} is not kebab-case")
        for n in s.seeds:
            if not (SEED_MIN <= n <= SEED_MAX):
                findings.append(f"AS2 spine claim {s.id!r} cites seed {n} outside the author's 1..10 set")
        if s.word_count > WORD_CAP:
            findings.append(f"AS2 spine claim {s.id!r} statement is {s.word_count} words (> {WORD_CAP}-word cap)")
    n = len(model.spine)
    if not (SPINE_MIN <= n <= SPINE_MAX):
        findings.append(f"AS2 spine has {n} claims — outside the directive's {SPINE_MIN}–{SPINE_MAX} band")
    if [s.order for s in model.spine] != list(range(1, n + 1)):
        findings.append("AS2 spine `order` values are not exactly 1..N contiguous")

    # AS3 — reconciliation links resolve.
    for s in model.spine:
        for cid in s.reconciles_claims:
            if cid not in claim_ids:
                findings.append(f"AS3 spine claim {s.id!r} reconciles unknown claim id {cid!r}")
        for slug in s.reconciles_big_ideas:
            if slug not in idea_slugs:
                findings.append(f"AS3 spine claim {s.id!r} reconciles unknown big-idea slug {slug!r}")

    # AS4 — reconciliation complete in the reverse direction.
    covered_claims = {cid for s in model.spine for cid in s.reconciles_claims}
    covered_ideas = {slug for s in model.spine for slug in s.reconciles_big_ideas}
    for cid in sorted(claim_ids - covered_claims):
        findings.append(f"AS4 claims-model id {cid!r} is reconciled by no spine claim")
    for slug in sorted(idea_slugs - covered_ideas):
        findings.append(f"AS4 big-idea {slug!r} is reconciled by no spine claim")

    # AS5 — exhaustive chapter labeling, keys == outline chapter slugs.
    decl = _load_declared()
    labeled = set(decl.get("chapter_advances", {}))
    outline_slugs = {c.slug for c in om.derive_outline().chapters}
    for slug in sorted(outline_slugs - labeled):
        findings.append(f"AS5 chapter {slug!r} carries no argument label (chapter_advances is exhaustive)")
    for slug in sorted(labeled - outline_slugs):
        findings.append(f"AS5 chapter_advances keys {slug!r} — the outline defines no such chapter")

    # AS6 — advanced ids resolve; no duplicates per chapter.
    spine_ids = {s.id for s in model.spine}
    for ch in model.chapters:
        if len(ch.advances) != len(set(ch.advances)):
            findings.append(f"AS6 chapter {ch.slug!r} lists a duplicate spine id")
        for sid in ch.advances:
            if sid not in spine_ids:
                findings.append(f"AS6 chapter {ch.slug!r} advances unknown spine id {sid!r}")

    # AS7 — exemption enum + keys.
    for slug, reason in decl.get("chapter_exemptions", {}).items():
        if reason not in EXEMPT_REASONS:
            findings.append(f"AS7 chapter {slug!r} exemption {reason!r} not in the closed enum "
                            f"({', '.join(EXEMPT_REASONS)})")
        if slug not in labeled:
            findings.append(f"AS7 exemption for {slug!r} — chapter carries no label row")
    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "SpineModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    flags = model.flags()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "spine_claims": len(model.spine),
            "chapters_labeled": sum(1 for c in model.chapters if c.advances),
            "chapters_exempt": sum(1 for c in model.chapters if c.exempt),
            "advancement_edges": sum(len(c.advances) for c in model.chapters),
            "reconciled_claims": len({cid for s in model.spine for cid in s.reconciles_claims}),
            "reconciled_big_ideas": len({b for s in model.spine for b in s.reconciles_big_ideas}),
            "zero_claim_suspects": len(flags["zero_claim_suspects"]),
            "over_cap_unfocused": len(flags["over_cap_unfocused"]),
            "max_statement_words": max((s.word_count for s in model.spine), default=0),
        },
        "taxonomy": {"word_cap": WORD_CAP, "focus_cap": FOCUS_CAP,
                     "spine_bounds": [SPINE_MIN, SPINE_MAX],
                     "exempt_reasons": list(EXEMPT_REASONS)},
        "spine": [asdict(s) for s in model.spine],
        "chapters": [asdict(c) for c in model.chapters],
        "flags": flags,
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['spine_claims']} spine claims; "
          f"{c['chapters_labeled']} chapters labeled ({c['advancement_edges']} edges, "
          f"{c['chapters_exempt']} exempt); flags: {c['zero_claim_suspects']} zero-claim, "
          f"{c['over_cap_unfocused']} over-cap")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """AS1-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    keys = ("spine", "chapters", "flags", "_counts")
    if any(stored.get(k) != fresh[k] for k in keys):
        print("DRIFT: argument-spine.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"argument-spine.json is in sync ({fresh['_counts']['spine_claims']} spine claims, "
          f"{fresh['_counts']['advancement_edges']} advancement edges)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _print_spine() -> int:
    model = derive_model()
    print("== the argument spine ==")
    for s in model.spine:
        seeds = f" [seeds {','.join(map(str, s.seeds))}]" if s.seeds else ""
        print(f"{s.order:>3}. {s.id}{seeds}\n     {s.statement}")
        if s.advanced_by:
            print(f"     advanced by: {', '.join(s.advanced_by)}")
    return 0


def _print_flags() -> int:
    flags = derive_model().flags()
    print("== focus flags (derived; the Phase-1c refactor worklist) ==")
    for f in flags["zero_claim_suspects"]:
        print(f"  ZERO-CLAIM suspect: {f['chapter']}")
    for f in flags["over_cap_unfocused"]:
        print(f"  OVER-CAP ({f['advances']} > {FOCUS_CAP}): {f['chapter']} — {', '.join(f['spine_ids'])}")
    if not flags["zero_claim_suspects"] and not flags["over_cap_unfocused"]:
        print("  none — every non-exempt chapter advances 1..3 spine claims")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "spine":
        return _print_spine()
    if cmd == "flags":
        return _print_flags()
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
