"""The CATALOGUE-CARDS view — Phase 3 · 3a of the editorial run (book/_design/phase3a-brief-260803.md).

One 9-field analysis CARD per catalogue entry, the empirical substrate for the 3b clustering step
(merge iff the first SIX fields — failure class / obligation / structure / guarantee / semantic level /
forces — are substantially the same and only known-uses differ; keep separate iff the obligation OR the
guarantee differs even under the same implementation technology). The card method is the directive's
"PRACTICAL METHOD — card + cluster" (book/_design/book-editorial-discipline-directive-260802.md,
Task 3 SUPPLEMENT).

DECLARED → GENERATED. The hand-authored analysis lives in catalogue_cards_declared.json (the 9 fields
per entry, plus optional `abstract_name` and `note`). This generator JOINS each card with the entry's
live INDEX.md census metadata (title · family · role · Form / Move / Model / Enf.) — read from INDEX.md
at generation time, never restated by hand — and writes catalogue-cards.json. If INDEX metadata moves,
regenerate; the cards can't silently drift from the census.

SEMANTIC-LEVEL discipline (BEWARE FALSE MERGERS): field 5 records the RELATION the mechanism models or
enforces (e.g. "implementation ⊨ semantic policy", "model ⟷ reality", "every mutation site →
provenance record"), never the enforcement technology. Two lints that enforce different relations are
different mechanisms; "uses a lint" is not a level.

Run `python3 book-models/catalogue_cards_model.py regenerate` to write the artifact;
`... verify` to drift-check (also fails if a declared id has no INDEX row);
`... status` for coverage (carded / pending per family).
"""
from __future__ import annotations

import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_DECLARED = os.path.join(_HERE, "catalogue_cards_declared.json")
_ARTIFACT = os.path.join(_HERE, "catalogue-cards.json")
_INDEX = os.path.join(_ROOT, "INDEX.md")

_PROVENANCE = (
    "GENERATED by book-models/catalogue_cards_model.py — do not hand-edit; regenerate with "
    "`python3 book-models/catalogue_cards_model.py regenerate`. The 9 analysis fields are hand-authored "
    "in book-models/catalogue_cards_declared.json; the census metadata (title/family/role/form/move/"
    "model/enf) is joined live from INDEX.md at generation time."
)

_MODEL_NOTE = (
    "Phase 3 · 3a card substrate for the 3b clustering (book/_design/phase3a-brief-260803.md; method: "
    "the editorial directive's 'card + cluster'). One card per catalogue entry: Failure class · "
    "Engineering obligation · Solution structure · Guarantee · Semantic level · Forces/tradeoffs · "
    "Dependencies · Known uses · Likely parent family, plus optional abstract_name (where the entry "
    "title is implementation-biased) and note (carding ambiguities, flagged for 3b). 3b merges entries "
    "whose first six fields substantially coincide (only known-uses differing) and keeps entries apart "
    "when obligation OR guarantee differs; semantic_level records the RELATION enforced/modeled, not "
    "the implementation technology. READ-ONLY wrt entries: this model analyzes the catalogue; it does "
    "not govern it."
)

_ROLE_BY_HEADING = {
    "Agent target": "agent",
    "Models-bridge": "models-bridge",
    "Product target": "product",
}

_CARD_FIELDS = (
    "failure_class",
    "engineering_obligation",
    "solution_structure",
    "guarantee",
    "semantic_level",
    "forces_tradeoffs",
    "dependencies",
    "known_uses",
    "likely_parent_family",
)
_OPTIONAL_FIELDS = ("abstract_name", "note")


def _strip_census_markers(text: str) -> str:
    return re.sub(r"<!--census:[^>]*-->|<!--/census-->", "", text)


def parse_index() -> dict[str, dict[str, str]]:
    """One record per census row, keyed by entry id (role-relative path minus .md)."""
    entries: dict[str, dict[str, str]] = {}
    role = family = None
    with open(_INDEX, encoding="utf-8") as f:
        for raw in f:
            line = _strip_census_markers(raw).rstrip("\n")
            h1 = re.match(r"^# (.+)$", line)
            if h1:
                role = _ROLE_BY_HEADING.get(h1.group(1).strip())
                continue
            h2 = re.match(r"^## (?:\d+\.\s*)?(.+)$", line)
            if h2:
                family = h2.group(1).strip()
                continue
            row = re.match(r"^\|\s*✅\s*\|(.+)\|\s*$", line)
            if not row:
                continue
            cells = [c.strip() for c in row.group(1).split("|")]
            if len(cells) != 6:
                raise SystemExit(f"INDEX row with {len(cells)} cells (expected 6): {line!r}")
            title, form, move, model, enf, entry = cells
            m = re.search(r"\]\(([^)]+\.md)\)", entry)
            if not m:
                raise SystemExit(f"INDEX row without entry link: {line!r}")
            entry_id = m.group(1)[: -len(".md")]
            # strip the trunk/product-facing italics annotation from bridge titles
            title = re.sub(r"\s*—\s*\*[^*]+\*\s*$", "", title).strip()
            entries[entry_id] = {
                "title": title,
                "role": role or "?",
                "family": family or "?",
                "form": form.strip("`"),
                "move": move.split("—")[0].strip().strip("`"),
                "model": model.strip("`"),
                "enf": enf,
            }
    return entries


def _load_declared() -> dict[str, dict[str, object]]:
    with open(_DECLARED, encoding="utf-8") as f:
        declared = json.load(f)
    return declared["cards"]


def build() -> dict[str, object]:
    index = parse_index()
    cards = _load_declared()
    unknown = sorted(set(cards) - set(index))
    if unknown:
        raise SystemExit(f"declared card(s) with no INDEX row: {unknown}")
    for entry_id, card in cards.items():
        missing = [f for f in _CARD_FIELDS if f not in card]
        if missing:
            raise SystemExit(f"{entry_id}: card missing field(s) {missing}")
        extra = [f for f in card if f not in _CARD_FIELDS + _OPTIONAL_FIELDS]
        if extra:
            raise SystemExit(f"{entry_id}: unknown field(s) {extra}")
    pending = sorted(set(index) - set(cards))
    family_dist: dict[str, int] = {}
    for card in cards.values():
        guess = str(card["likely_parent_family"])
        family_dist[guess] = family_dist.get(guess, 0) + 1
    by_role: dict[str, int] = {}
    for entry_id in cards:
        by_role[index[entry_id]["role"]] = by_role.get(index[entry_id]["role"], 0) + 1
    out_entries = {}
    for entry_id in sorted(index):
        if entry_id not in cards:
            continue
        meta = index[entry_id]
        card = cards[entry_id]
        out_entries[entry_id] = {
            "title": meta["title"],
            "role": meta["role"],
            "family": meta["family"],
            "index_metadata": {k: meta[k] for k in ("form", "move", "model", "enf")},
            "card": {k: card[k] for k in _CARD_FIELDS + _OPTIONAL_FIELDS if k in card},
        }
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "census_total": len(index),
            "carded": len(cards),
            "pending": pending,
            "carded_by_role": by_role,
            "likely_parent_family_distribution": dict(
                sorted(family_dist.items(), key=lambda kv: (-kv[1], kv[0]))
            ),
        },
        "entries": out_entries,
    }


def regenerate() -> None:
    artifact = build()
    with open(_ARTIFACT, "w", encoding="utf-8") as f:
        json.dump(artifact, f, indent=2, ensure_ascii=False)
        f.write("\n")
    counts = artifact["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT, _ROOT)}: "
          f"{counts['carded']}/{counts['census_total']} carded "
          f"({len(counts['pending'])} pending)")


def verify() -> int:
    artifact = build()
    if not os.path.exists(_ARTIFACT):
        print("catalogue-cards.json missing — run regenerate", file=sys.stderr)
        return 1
    with open(_ARTIFACT, encoding="utf-8") as f:
        on_disk = json.load(f)
    if on_disk != artifact:
        print("catalogue-cards.json is stale — run regenerate", file=sys.stderr)
        return 1
    print("catalogue-cards.json is current")
    return 0


def status() -> None:
    index = parse_index()
    cards = _load_declared()
    per_family: dict[str, list[int]] = {}
    for entry_id, meta in index.items():
        fam = f"{meta['role']} · {meta['family']}"
        tot = per_family.setdefault(fam, [0, 0])
        tot[0] += 1
        if entry_id in cards:
            tot[1] += 1
    for fam, (total, carded) in per_family.items():
        mark = "✓" if carded == total else " "
        print(f"[{mark}] {carded:2d}/{total:2d}  {fam}")
    print(f"total {len(cards)}/{len(index)}")


def main(argv: list[str]) -> int:
    cmd = argv[1] if len(argv) > 1 else "status"
    if cmd == "regenerate":
        regenerate()
        return 0
    if cmd == "verify":
        return verify()
    if cmd == "status":
        status()
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
