"""The CHAPTER-SHAPE view — a typed model of each chapter's OPENING and CLOSING shape against the
editorial discipline (directive book/_design/book-editorial-discipline-directive-260802.md Part A Task 2 /
Part B Phase 2). The seventh sibling model beside outline / outcomes / concepts / big-ideas / claims /
argument-spine.

THE DISCIPLINE IT ENCODES.  Every chapter OPENING should identify (1) the failure or question the chapter
addresses, (2) the chapter's answer, and (3) how the chapter advances one of the book's two theses
(Modeling / Alignment) — or, for chapters whose spine labels carry neither thesis directly, its step in the
argument. Every chapter ENDING should be ONE of: a concrete consequence, a transition to the next
unresolved problem, or a concise synthesis — and must NOT merely re-announce the chapter's thesis.

WHY A NEW MODEL, NOT AN EXTENSION.  The outline model is derived from the book on every run — it has no
hand-authored source an editorial judgment could live in. The outcomes model is pedagogical (what the
reader can do), not rhetorical (how the chapter opens and lands). The argument-spine holds WHAT each
chapter advances; this model holds HOW the chapter's first and last prose carry it. Same homing rule that
earned the spine its own file: distinctive fields that belong to no sibling.

JOIN, DON'T RESTATE.  Chapter exemptions (preface / conclusion / discussion / end-of-part-synthesis /
apparatus / overview) are JOINED from the argument-spine's declared source at derive time — a single
source of truth, no second copy. The spine's per-chapter `advances` labels are likewise read live for the
thesis-consistency flag.

ASSESSMENTS ARE HAND-AUTHORED; FLAGS ARE DERIVED.  chapter_shape_declared.json records, per chapter, the
2a editorial assessment: presence of each opening element (explicit / implicit / absent), the thesis the
opening claims (modeling / alignment / both / argument-step / none), the closing's kind, and a short
evidence note. The generator derives the FLAG worklist (never authored, mirroring the spine's focus
flags): a non-exempt chapter whose opening lacks an element outright, whose closing is a bad kind
(apparatus / mid-taxonomy / re-announcement), or whose claimed thesis mismatches its spine labels. Exempt
chapters are assessed but never flagged — softer treatment per the directive.

ANCHORS FREEZE THE ASSESSED PROSE.  Each declared record carries `opening_anchor` / `closing_anchor` — the
first / last words of the prose the assessment was made against. The CS5 staleness check re-derives the
chapter's current opening/closing prose from the book (via book_ir) and fails the anchor when the prose
has changed: a rewritten opening (the Phase-2c refactor) invalidates its assessment loudly instead of
letting the model describe prose that no longer exists. Regenerating the artifact never refreshes an
anchor; only a re-assessment (editing the declared file) does.

Run `python3 book-models/chapter_shape_model.py regenerate` to write chapter-shape.json; `... verify` to
drift-check; `... flags` to print the derived worklist; `... anchors <slug>` to print a chapter's current
anchor words (for re-assessment).
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import outline_model as om  # noqa: E402 — the outline view supplies the chapter tree

_HERE = os.path.dirname(os.path.abspath(__file__))
_BOOK = os.path.join(os.path.dirname(_HERE), "book")
if _BOOK not in sys.path:
    sys.path.insert(0, _BOOK)
import book_ir  # noqa: E402 — the chapter prose the anchors freeze

_ARTIFACT = os.path.join(_HERE, "chapter-shape.json")
_DECLARED = os.path.join(_HERE, "chapter_shape_declared.json")
_SPINE_DECLARED = os.path.join(_HERE, "argument_spine_declared.json")

_PROVENANCE = ("GENERATED by book-models/chapter_shape_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/chapter_shape_model.py regenerate`. Derived from the hand-authored "
               "assessments in book-models/chapter_shape_declared.json, joined against the argument-spine's "
               "declared labels + exemptions and the outline's chapter tree.")

_MODEL_NOTE = (
    "The chapter-shape model records each chapter's opening/closing assessment against the editorial "
    "discipline: an opening names the failure or question, the chapter's answer, and the thesis (or "
    "argument step) it advances; a closing is a concrete consequence, a transition, or a synthesis — "
    "never a mere thesis re-announcement. The `flags` block is DERIVED editorial signal (the Phase-2c "
    "refactor worklist) and never gates; exempt chapters are assessed but not flagged. Anchors freeze "
    "the prose each assessment was made against — a rewrite invalidates the assessment loudly (CS5).")

#: Presence grades for the three opening elements. `implicit` passes with a note (the element is carried
#: by content but not stated); only `absent` flags.
PRESENCE = ("explicit", "implicit", "absent")

#: What the opening claims the chapter advances. `argument-step` = a spine claim other than the two
#: theses; `none` is only coherent with an absent thesis link (CS4).
THESIS_TARGETS = ("modeling", "alignment", "both", "argument-step", "none")

#: Closing kinds. The first three satisfy the discipline; the last three flag.
CLOSING_GOOD = ("consequence", "transition", "synthesis")
CLOSING_BAD = ("apparatus", "mid-taxonomy", "re-announcement")
CLOSING_KINDS = CLOSING_GOOD + CLOSING_BAD

#: Words per anchor — enough to pin a paragraph identity, short enough to review at a glance.
ANCHOR_WORDS = 12

#: The spine claim ids that ARE the two theses — the CS-mismatch join keys.
MODELING_ID, ALIGNMENT_ID = "modeling-thesis", "alignment-thesis"

#: Boilerplate blockquote lead that never counts as closing prose (a cross-reference, not an ending).
_LEARN_MORE = "> Learn more about"

_PROSE_KINDS = {book_ir.BlockKind.PARA, book_ir.BlockKind.LIST,
                book_ir.BlockKind.ORDERED_LIST, book_ir.BlockKind.BLOCKQUOTE}


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class OpeningShape:
    """The three-element opening assessment. Each element ∈ PRESENCE; `thesis_target` names what the
    opening claims to advance (∈ THESIS_TARGETS)."""
    failure_question: str
    answer: str
    thesis_link: str
    thesis_target: str


@dataclass
class ClosingShape:
    """The closing assessment: its primary kind (∈ CLOSING_KINDS)."""
    kind: str


@dataclass
class ChapterShape:
    slug: str
    opening: OpeningShape
    closing: ClosingShape
    note: str
    opening_anchor: str
    closing_anchor: str
    exempt: "str | None" = None                       # joined from the argument-spine's declared source
    spine_advances: list[str] = field(default_factory=list)  # joined; the thesis-mismatch join input


@dataclass
class ShapeModel:
    chapters: list[ChapterShape]

    def flags(self) -> "dict[str, list[dict]]":
        """The DERIVED refactor worklist (never authored; exempt chapters never flag).
        - failing_openings: a required element graded `absent`.
        - failing_closings: kind ∈ CLOSING_BAD.
        - thesis_spine_mismatches: the opening claims a thesis the chapter's spine labels do not carry."""
        openings, closings, mismatches = [], [], []
        for c in self.chapters:
            if c.exempt:
                continue
            missing = [name for name, grade in (("failure/question", c.opening.failure_question),
                                                ("answer", c.opening.answer),
                                                ("thesis-link", c.opening.thesis_link)) if grade == "absent"]
            if missing:
                openings.append({"chapter": c.slug, "missing": missing, "note": c.note})
            if c.closing.kind in CLOSING_BAD:
                closings.append({"chapter": c.slug, "kind": c.closing.kind, "note": c.note})
            need = {"modeling": {MODELING_ID}, "alignment": {ALIGNMENT_ID},
                    "both": {MODELING_ID, ALIGNMENT_ID}}.get(c.opening.thesis_target, set())
            if need and not need <= set(c.spine_advances):
                mismatches.append({"chapter": c.slug, "claimed": c.opening.thesis_target,
                                   "spine_advances": list(c.spine_advances)})
        return {"failing_openings": openings, "failing_closings": closings,
                "thesis_spine_mismatches": mismatches}


# ---- prose extraction (the anchor substrate) --------------------------------------------------------

def _norm(words: "list[str]") -> str:
    return " ".join(words)


def chapter_prose_anchors(ch: "book_ir.Chapter") -> "tuple[str, str]":
    """(opening_anchor, closing_anchor) for a chapter's CURRENT prose.

    Opening prose = the prose blocks after the H1 title and before the first level-2+ heading (the
    untitled lead). A chapter with no lead (it opens straight into its first section) anchors on the
    first section's prose instead — the assessment covered that prose, so the anchor must too.
    Closing prose = the chapter's last prose block, skipping `Learn more` cross-reference blockquotes
    (boilerplate, not an ending — an ending rewrite behind one must still trip the anchor)."""
    lead: "list[str]" = []
    seen_h1 = False
    for b in ch.blocks:
        if b.kind == book_ir.BlockKind.HEADING:
            if b.heading_level == 1 and not seen_h1:
                seen_h1 = True
                continue
            if b.heading_level >= 2:
                break
        if b.kind in _PROSE_KINDS:
            lead.append(b.raw.strip())
    if not lead:  # no untitled lead — anchor the first section's prose
        past_first_heading = False
        for b in ch.blocks:
            if b.kind == book_ir.BlockKind.HEADING and b.heading_level >= 2:
                if past_first_heading:
                    break
                past_first_heading = True
                continue
            if past_first_heading and b.kind in _PROSE_KINDS:
                lead.append(b.raw.strip())
    opening_words = " ".join(lead).split()

    closing_words: "list[str]" = []
    for b in reversed(ch.blocks):
        if b.kind in _PROSE_KINDS and not b.raw.strip().startswith(_LEARN_MORE):
            closing_words = b.raw.strip().split()
            break
    return (_norm(opening_words[:ANCHOR_WORDS]), _norm(closing_words[-ANCHOR_WORDS:]))


def current_anchors() -> "dict[str, tuple[str, str]]":
    doc = book_ir.parse_book()
    return {ch.slug: chapter_prose_anchors(ch) for ch in doc.chapters}


# ---- load + build -----------------------------------------------------------------------------------

def _load_json(path: str) -> "dict | None":
    return json.load(open(path, encoding="utf-8")) if os.path.isfile(path) else None


def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def _spine_joins() -> "tuple[dict[str, str], dict[str, list[str]]]":
    """(exemptions, advances) joined live from the argument-spine's declared source — no snapshot."""
    spine = _load_json(_SPINE_DECLARED) or {}
    return dict(spine.get("chapter_exemptions", {})), dict(spine.get("chapter_advances", {}))


def derive_model() -> ShapeModel:
    """Build the shape model from the declared assessments, joined against the spine (exemptions +
    advances). Chapters follow the outline's order; an assessment keyed to a chapter the outline no
    longer defines still surfaces (CS2 reddens it)."""
    decl = _load_declared()
    by_slug = {a["slug"]: a for a in decl.get("assessments", [])}
    exemptions, advances = _spine_joins()

    def _build(slug: str) -> ChapterShape:
        a = by_slug[slug]
        return ChapterShape(
            slug=slug,
            opening=OpeningShape(failure_question=a["opening"]["failure_question"],
                                 answer=a["opening"]["answer"],
                                 thesis_link=a["opening"]["thesis_link"],
                                 thesis_target=a["opening"]["thesis_target"]),
            closing=ClosingShape(kind=a["closing"]["kind"]),
            note=a.get("note", ""),
            opening_anchor=a.get("opening_anchor", ""),
            closing_anchor=a.get("closing_anchor", ""),
            exempt=exemptions.get(slug),
            spine_advances=list(advances.get(slug, [])),
        )

    chapters = [_build(c.slug) for c in om.derive_outline().chapters if c.slug in by_slug]
    known = {c.slug for c in om.derive_outline().chapters}
    for slug in by_slug:
        if slug not in known:
            chapters.append(_build(slug))
    return ShapeModel(chapters=chapters)


# ---- invariants (CS1–CS5; walked by the drift check in tests/book_models.py) -------------------------

def structural_findings(model: "ShapeModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants. Deterministic; the flag worklist is NOT findings (it is the
    artifact's `flags` block — editorial signal, mirroring the spine's focus flags).

    CS2 — assessment coverage is exhaustive and exact: declared slugs == the outline's chapter slugs.
    CS3 — enum membership: every presence grade ∈ PRESENCE, thesis_target ∈ THESIS_TARGETS,
          closing kind ∈ CLOSING_KINDS; no duplicate slugs.
    CS4 — coherence: thesis_target == 'none' iff thesis_link == 'absent'.
    CS5 — anchor freshness: each declared anchor equals the chapter's CURRENT opening/closing prose
          words — a rewritten opening or ending invalidates its assessment loudly.

    (CS1, drift — the artifact equals a fresh derivation — is walked by the tests/book_models.py check
    and the `verify` CLI, mirroring the siblings.)"""
    if model is None:
        model = derive_model()
    findings: "list[str]" = []
    decl = _load_declared()
    declared_slugs = [a["slug"] for a in decl.get("assessments", [])]

    # CS2 — exhaustive + exact coverage of the outline's chapters.
    outline_slugs = {c.slug for c in om.derive_outline().chapters}
    for slug in sorted(outline_slugs - set(declared_slugs)):
        findings.append(f"CS2 chapter {slug!r} carries no shape assessment (coverage is exhaustive)")
    for slug in sorted(set(declared_slugs) - outline_slugs):
        findings.append(f"CS2 assessment for {slug!r} — the outline defines no such chapter")

    # CS3 — enums + uniqueness.
    if len(declared_slugs) != len(set(declared_slugs)):
        findings.append("CS3 duplicate assessment slug in chapter_shape_declared.json")
    for c in model.chapters:
        for name, grade in (("failure_question", c.opening.failure_question),
                            ("answer", c.opening.answer), ("thesis_link", c.opening.thesis_link)):
            if grade not in PRESENCE:
                findings.append(f"CS3 {c.slug!r} opening.{name} {grade!r} not in {PRESENCE}")
        if c.opening.thesis_target not in THESIS_TARGETS:
            findings.append(f"CS3 {c.slug!r} thesis_target {c.opening.thesis_target!r} not in {THESIS_TARGETS}")
        if c.closing.kind not in CLOSING_KINDS:
            findings.append(f"CS3 {c.slug!r} closing.kind {c.closing.kind!r} not in {CLOSING_KINDS}")

    # CS4 — `none` coherent with an absent link, both ways.
    for c in model.chapters:
        if (c.opening.thesis_target == "none") != (c.opening.thesis_link == "absent"):
            findings.append(f"CS4 {c.slug!r}: thesis_target {c.opening.thesis_target!r} incoherent with "
                            f"thesis_link {c.opening.thesis_link!r} ('none' iff 'absent')")

    # CS5 — anchors match the CURRENT prose (assessment-staleness guard for the 2c refactor).
    fresh = current_anchors()
    for c in model.chapters:
        pair = fresh.get(c.slug)
        if pair is None:
            continue  # CS2 already reddens a vanished chapter
        if c.opening_anchor != pair[0]:
            findings.append(f"CS5 {c.slug!r} opening prose changed since assessment — re-assess "
                            f"(declared anchor {c.opening_anchor!r} vs current {pair[0]!r})")
        if c.closing_anchor != pair[1]:
            findings.append(f"CS5 {c.slug!r} closing prose changed since assessment — re-assess "
                            f"(declared anchor {c.closing_anchor!r} vs current {pair[1]!r})")
    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "ShapeModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    flags = model.flags()
    non_exempt = [c for c in model.chapters if not c.exempt]
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "chapters_assessed": len(model.chapters),
            "chapters_exempt": sum(1 for c in model.chapters if c.exempt),
            "openings_failing": len(flags["failing_openings"]),
            "closings_failing": len(flags["failing_closings"]),
            "thesis_spine_mismatches": len(flags["thesis_spine_mismatches"]),
            "openings_implicit_thesis": sum(1 for c in non_exempt if c.opening.thesis_link == "implicit"),
        },
        "taxonomy": {"presence": list(PRESENCE), "thesis_targets": list(THESIS_TARGETS),
                     "closing_good": list(CLOSING_GOOD), "closing_bad": list(CLOSING_BAD),
                     "anchor_words": ANCHOR_WORDS},
        "chapters": [asdict(c) for c in model.chapters],
        "flags": flags,
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['chapters_assessed']} chapters assessed "
          f"({c['chapters_exempt']} exempt); flags: {c['openings_failing']} failing openings, "
          f"{c['closings_failing']} failing closings, {c['thesis_spine_mismatches']} thesis mismatches")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """CS1-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    keys = ("chapters", "flags", "_counts")
    if any(stored.get(k) != fresh[k] for k in keys):
        print("DRIFT: chapter-shape.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"chapter-shape.json is in sync ({fresh['_counts']['chapters_assessed']} chapters, "
          f"{fresh['_counts']['openings_failing']}+{fresh['_counts']['closings_failing']} flags)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _print_flags() -> int:
    flags = derive_model().flags()
    print("== chapter-shape flags (derived; the Phase-2c refactor worklist) ==")
    for f in flags["failing_openings"]:
        print(f"  OPENING {f['chapter']}: missing {', '.join(f['missing'])}")
    for f in flags["failing_closings"]:
        print(f"  CLOSING {f['chapter']}: kind={f['kind']}")
    for f in flags["thesis_spine_mismatches"]:
        print(f"  THESIS-MISMATCH {f['chapter']}: opening claims {f['claimed']!r}, "
              f"spine advances {f['spine_advances']}")
    if not any(flags.values()):
        print("  none — every non-exempt chapter opens and closes to the discipline")
    return 0


def _print_anchors(slug: "str | None") -> int:
    for s, (o, c) in sorted(current_anchors().items()):
        if slug and s != slug:
            continue
        print(f"{s}\n  opening: {o!r}\n  closing: {c!r}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "flags":
        return _print_flags()
    if cmd == "anchors":
        return _print_anchors(argv[2] if len(argv) > 2 else None)
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
