"""The design-token PROJECTOR — one typed SSOT (`design-tokens.json`), three renderer projections.

The repo's own thesis, applied to its own styling: project the artifact from a typed model, then gate
drift. `design-tokens.json` is the single source of truth for the Umber-Monograph visual system (warm
paper, burnt-umber accent, a Fraunces display face, one 8-step type scale addressed by ROLE, and the
decided semantic-box anchors — thesis GREEN, definition BLUE, inset LAVENDER). This module reads it and
emits each renderer's native form so the three surfaces (site / web book / PDF) cannot diverge:

    css_root_block()   -> ":root { --ink:#1c1917; --fs-body:18px; … }"   (site + web book inline this)
    typst_preamble()   -> "#let dt = (ink: rgb(\"#1c1917\"), fs-body: 13.5pt, …)" (PDF prepends this)
    mermaid_theme()     -> themeVariables dict for book/assets/mermaid-config.json (emitted artifact)
    svg_palette()       -> frozenset of every sanctioned hex (the hand-drawn-SVG membership set)
    google_fonts_link() -> the <link> that loads the display/body/mono web fonts

STDLIB-ONLY (`json`, `pathlib`, `argparse`) so `python3 catalog.py …` stays clone-and-run. Sits beside
the other model tooling (`outline_model.py`, `outcomes_model.py`).

CLI:
    python3 book-models/design_tokens.py css            # print the CSS :root block
    python3 book-models/design_tokens.py typst          # print the Typst #let dt preamble
    python3 book-models/design_tokens.py palette        # print the SVG palette allow-list
    python3 book-models/design_tokens.py emit-mermaid    # regenerate book/assets/mermaid-config.json
    python3 book-models/design_tokens.py check-mermaid   # verify the config equals the emitter (exit 1 if stale)
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from dataclasses import dataclass

HERE = pathlib.Path(__file__).resolve().parent
TOKENS_JSON = HERE / "design-tokens.json"
MERMAID_CONFIG = HERE.parent / "book" / "assets" / "mermaid-config.json"

# px → pt conversion for the print projection (96px == 72pt, so 1px == 0.75pt). Keeps screen and print
# proportional: re-ratio the scale once and both surfaces follow.
_PX_TO_PT = 0.75


@dataclass(frozen=True)
class Tokens:
    """Typed accessors over the SSOT. `palette` and the type/space/radius/border groups are raw dicts;
    the `px`/`pt`/`hex_` helpers resolve role names so call sites never index the scale array directly."""

    raw: dict

    @property
    def option(self) -> str:
        return self.raw["option"]

    @property
    def palette(self) -> dict:
        return self.raw["palette"]

    @property
    def type(self) -> dict:
        return self.raw["type"]

    def hex_(self, role: str) -> str:
        return self.palette[role]

    def _scale(self) -> list[int]:
        return self.type["scale-px"]

    def _role_index(self, role: str) -> int:
        return self.type["roles"][role]

    def px(self, role: str) -> int:
        """Font-size in px for a type ROLE (`body`, `card-title`, `display`, …)."""
        return self._scale()[self._role_index(role)]

    def pt(self, role: str) -> float:
        return round(self.px(role) * _PX_TO_PT, 2)

    def space(self, i: int) -> int:
        return self.raw["space-px"][i]

    def radius(self, name: str) -> int:
        return self.raw["radius-px"][name]

    def border(self, name: str) -> int:
        return self.raw["border-px"][name]

    def css_stack(self, kind: str) -> str:
        return self.type[kind]["css-stack"]

    def typst_stack(self, kind: str) -> list[str]:
        return self.type[kind]["typst-stack"]


def load(path: pathlib.Path = TOKENS_JSON) -> Tokens:
    with open(path, encoding="utf-8") as fh:
        return Tokens(json.load(fh))


# ── CSS projection ──────────────────────────────────────────────────────────────────────────────────
# Custom-property names are the cross-renderer contract. Palette keys map 1:1 to `--<key>`; type roles
# become `--fs-<role>`; spacing/radii/borders/line-heights get stable names. Both catalog.py (site) and
# build_book_html.py (web book) inline this block at the top of their style, then reference var(--…).

_ROLE_ORDER = ["micro", "meta", "card-body", "body", "card-title", "section", "thesis-title", "display"]


def css_root_block(t: Tokens | None = None) -> str:
    t = t or load()
    lines: list[str] = [
        "  /* GENERATED by book-models/design_tokens.py from design-tokens.json — do not hand-edit. */",
        "  :root {",
    ]
    for key, val in t.palette.items():
        lines.append(f"    --{key}: {val};")
    lines.append(f"    --font-display: {t.css_stack('display')};")
    lines.append(f"    --font-body: {t.css_stack('body')};")
    lines.append(f"    --font-mono: {t.css_stack('mono')};")
    disp = t.type["display"]
    lines.append(f"    --display-weight: {disp['display-weight']};")
    lines.append(f"    --display-tracking: {disp['display-tracking-em']}em;")
    for role in _ROLE_ORDER:
        lines.append(f"    --fs-{role}: {t.px(role)}px;")
    lh = t.type["line-height"]
    lines.append(f"    --lh-body: {lh['body']};")
    lines.append(f"    --lh-display: {lh['display']};")
    lines.append(f"    --lh-card: {lh['card']};")
    for i, _ in enumerate(t.raw["space-px"]):
        lines.append(f"    --space-{i}: {t.space(i)}px;")
    for name in t.raw["radius-px"]:
        lines.append(f"    --radius-{name}: {t.radius(name)}px;")
    for name in t.raw["border-px"]:
        lines.append(f"    --border-{name}: {t.border(name)}px;")
    lines.append("  }")
    return "\n".join(lines) + "\n"


def google_fonts_link(t: Tokens | None = None) -> str:
    """The <link> loading the display (Fraunces), body (Source Sans 3), and mono (IBM Plex Mono) faces."""
    return (
        '<link rel="preconnect" href="https://fonts.googleapis.com">'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
        '<link href="https://fonts.googleapis.com/css2?'
        "family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&"
        "family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&"
        'family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">'
    )


# ── Typst projection ────────────────────────────────────────────────────────────────────────────────
# `#let dt = ( … )` — colors as rgb("#…"), sizes as pt, font stacks as ("A", "B"). book_typst.py prepends
# this and looks up dt.ink / dt.fs-body / dt.box-thesis-rule … instead of literal hexes and luma() grays.


def _typst_font_tuple(stack: list[str]) -> str:
    return "(" + ", ".join(f'"{f}"' for f in stack) + ")"


def typst_preamble(t: Tokens | None = None) -> str:
    t = t or load()
    lines: list[str] = [
        "// GENERATED by book-models/design_tokens.py from design-tokens.json — do not hand-edit.",
        "#let dt = (",
    ]
    for key, val in t.palette.items():
        lines.append(f'  "{key}": rgb("{val}"),')
    lines.append(f'  "font-display": {_typst_font_tuple(t.typst_stack("display"))},')
    lines.append(f'  "font-body": {_typst_font_tuple(t.typst_stack("body"))},')
    lines.append(f'  "font-mono": {_typst_font_tuple(t.typst_stack("mono"))},')
    for role in _ROLE_ORDER:
        lines.append(f'  "fs-{role}": {t.pt(role)}pt,')
    for i, _ in enumerate(t.raw["space-px"]):
        lines.append(f'  "space-{i}": {round(t.space(i) * _PX_TO_PT, 2)}pt,')
    for name in t.raw["radius-px"]:
        lines.append(f'  "radius-{name}": {round(t.radius(name) * _PX_TO_PT, 2)}pt,')
    for name in t.raw["border-px"]:
        lines.append(f'  "border-{name}": {round(t.border(name) * _PX_TO_PT, 2)}pt,')
    disp = t.type["display"]
    lines.append(f'  "display-weight": {disp["display-weight"]},')
    lines.append(f'  "display-tracking": {disp["display-tracking-em"]}em,')
    lines.append(")")
    return "\n".join(lines) + "\n"


# ── Mermaid projection ──────────────────────────────────────────────────────────────────────────────
# The interior mermaid figures theme from the tokens (body sans, not Georgia serif; size = the card-body
# scale step). Emitted artifact, provenance-keyed — the freshness gate re-emits and compares.


def mermaid_theme(t: Tokens | None = None) -> dict:
    t = t or load()
    body_family = t.css_stack("body")
    return {
        "_provenance": "GENERATED by book-models/design_tokens.py (emit-mermaid) from design-tokens.json — do not hand-edit.",
        "startOnLoad": False,
        "securityLevel": "loose",
        "theme": "base",
        "htmlLabels": False,
        "themeVariables": {
            "fontFamily": body_family,
            "fontSize": f"{t.px('card-body')}px",
            "primaryColor": t.hex_("panel"),
            "primaryTextColor": t.hex_("ink"),
            "primaryBorderColor": t.hex_("muted"),
            "lineColor": t.hex_("muted"),
            "secondaryColor": t.hex_("diagram-governed-fill"),
            "tertiaryColor": t.hex_("accent-tint"),
        },
        "flowchart": {"htmlLabels": False, "nodeSpacing": 55, "rankSpacing": 60, "padding": 12},
        "sequence": {"actorFontSize": t.px("card-body"), "messageFontSize": t.px("micro"),
                     "noteFontSize": t.px("micro"), "width": 170, "height": 55},
        "state": {"titleTopMargin": 12},
        "er": {"fontSize": t.px("micro")},
        "class": {},
    }


def emit_mermaid(t: Tokens | None = None) -> str:
    payload = json.dumps(mermaid_theme(t), indent=2) + "\n"
    MERMAID_CONFIG.write_text(payload, encoding="utf-8")
    return payload


def mermaid_is_fresh(t: Tokens | None = None) -> bool:
    if not MERMAID_CONFIG.exists():
        return False
    want = json.dumps(mermaid_theme(t), indent=2) + "\n"
    return MERMAID_CONFIG.read_text(encoding="utf-8") == want


# ── SVG palette allow-list ──────────────────────────────────────────────────────────────────────────
# Every fill/stroke hex in a hand-drawn figure must be a member of this set. Includes the semantic
# palette plus a small neutrals set the drawings use for text/outlines (all lowercase, both #rrggbb and
# the pure ink/paper/white).


def svg_palette(t: Tokens | None = None) -> frozenset[str]:
    t = t or load()
    members = {v.lower() for v in t.palette.values()}
    # Neutrals the figures may use for hairlines, text, and page ground.
    members.update({"#ffffff", "#fff", "none", "#000000"})
    return frozenset(members)


# ── CLI ─────────────────────────────────────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["css", "typst", "palette", "emit-mermaid", "check-mermaid"])
    args = ap.parse_args(argv)
    t = load()
    if args.cmd == "css":
        sys.stdout.write(css_root_block(t))
    elif args.cmd == "typst":
        sys.stdout.write(typst_preamble(t))
    elif args.cmd == "palette":
        sys.stdout.write("\n".join(sorted(svg_palette(t))) + "\n")
    elif args.cmd == "emit-mermaid":
        emit_mermaid(t)
        sys.stdout.write(f"wrote {MERMAID_CONFIG}\n")
    elif args.cmd == "check-mermaid":
        if not mermaid_is_fresh(t):
            sys.stderr.write("mermaid-config.json is STALE — run: design_tokens.py emit-mermaid\n")
            return 1
        sys.stdout.write("mermaid-config.json is fresh\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
