"""The FLAGSHIP-STACK view — a typed model of the alternative appendix's deep-dive PACKAGES. A flagship
stack is not one mechanism but several catalogue entries that reinforce each other into one governed
capability; this model makes the deep-dive TEMPLATE mechanically checkable, sibling to chapter-shape and
argument-spine in book-models/.

WHY A NEW MODEL, NOT AN EXTENSION.  The catalogue-classification model holds `compositions` — which L2
PATTERNS join, and why. A flagship stack is a different object: a reader-facing deep-dive whose unit is the
catalogue ENTRY (the shipped mechanism), carrying fields no sibling holds — a one-line goal, the GEE
capability it serves, an overview figure asset, and, per part, the six-field template the page renders
(role · failure · mechanism · seam · durability). The seam field — how each part hands off to the one
beside it — is the interlocking story a package exists to tell, and it lives nowhere else. A new object
with fields none of the siblings carry earns its own file, the same rule that earned the claims and spine
models theirs.

READ THE CATALOGUE, DON'T COPY IT.  A part is a `slug` that JOINS to a real catalogue entry. The model
does not restate the entry's own Intent or metadata; it names the entry and adds the stack-local judgment
(what this part contributes HERE, and how it interlocks). FS1 holds the join: every `parts[].slug` resolves
to an entry file on disk, read at check time — a single source of truth, no snapshot.

THE CONFORMANCE CHECK (FS1–FS5) IS AUDIT-ONLY FIRST.  Following the repo's blocking-lint landing
discipline, the check reports but does not gate while the model carries a single record. A stack page that
drops a part field or an overview figure reddens the audit; a follow-up promotes it to blocking once all
seven stacks are populated and a clean session confirms the drain.

- FS1 — JOIN INTEGRITY: every `parts[].slug` resolves to a real catalogue entry.
- FS2 — PAGE SHAPE: every stack carries a non-empty goal, an overview_figure asset that EXISTS on disk, and
  at least MIN_PARTS parts, each with all six template fields non-empty.
- FS3 — FIGURE HOUSE-RULES: the overview_figure passes the figure-overflow sensor (text fits its box) and
  the design-token palette (every fill/stroke hex is a token).
- FS4 — COVERAGE (deferred while under-populated): the stacks' part-sets, mapped to their L2 patterns,
  should cover the classification's strong compositions' members, minus the author's documented moves. With
  fewer than the full seven records this is a DEFERRED note, not a finding.
- FS5 — FRESHNESS (optional): a stack's page source renders exactly its model part-set — the overview
  figure and every part slug appear in the page markdown, so a page that drifts from the record reddens.

Run `python3 book-models/flagship_stack_model.py regenerate` to write the artifact; `... verify` to
drift-check; `... list` to print the stacks; `... flagship <id>` to print one stack's parts + seams.
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import asdict, dataclass, field

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)  # the catalogue root — entry .md files live under <role>/<family>/<slug>.md
_ARTIFACT = os.path.join(_HERE, "flagship-stack.json")
_DECLARED = os.path.join(_HERE, "flagship_stack_declared.json")
_CLASSIFICATION = os.path.join(_HERE, "catalogue-classification.json")

_PROVENANCE = ("GENERATED by book-models/flagship_stack_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/flagship_stack_model.py regenerate`. Derived from the hand-authored "
               "flagship_stack_declared.json, resolved against the catalogue entries on disk.")

_MODEL_NOTE = (
    "The flagship-stack model holds the alternative appendix's deep-dive PACKAGES — several catalogue "
    "entries that reinforce each other into one governed capability. Each record carries a one-line goal, "
    "the GEE capability it serves, an overview figure, and one part per member with the six-field template "
    "the deep-dive renders (role · failure · mechanism · seam · durability). The FS1–FS5 conformance check "
    "holds the template mechanically: join integrity, page shape, figure house-rules, coverage, freshness. "
    "It lands audit-only-first — a page that drops a part field or its overview figure reddens the audit "
    "but does not gate while the model carries fewer than the full seven stacks.")

#: The six per-part template fields — the reusable deep-dive shape. FS2 holds each non-empty.
PART_FIELDS = ("role", "failure", "mechanism", "seam", "durability")

#: A deep-dive needs at least this many interlocking parts to be a stack rather than a lone mechanism.
MIN_PARTS = 2

#: The full flagship set the author finalized (reframe 260803). While the model carries fewer than this
#: many records, FS4 coverage is DEFERRED — the stacks are still being populated. Once all are in, FS4
#: promotes from a deferred note to a real coverage finding.
EXPECTED_STACKS = 7


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Part:
    """One member of a flagship stack. `slug` joins to a catalogue entry (FS1); the five template fields
    are the stack-LOCAL judgment the deep-dive renders — what this part contributes here, the failure it
    retires, the shape that prevents it, its interlock with the adjacent parts (`seam`), and its limits."""
    slug: str
    role: str
    failure: str
    mechanism: str
    seam: str
    durability: str
    resolves: bool = False  # derived (FS1): the slug names a real catalogue entry


@dataclass
class FlagshipStack:
    """One flagship deep-dive: a package of catalogue entries serving one or more GEE capabilities.
    `capabilities` is a list of ≥1 GEE capability names — most stacks serve one, but a stack can span two
    (the provenance + fidelity stack serves both *track provenance* and *preserve product semantics*).
    `overview_figure` is the self-communicate SVG the page leads with; `parts` are the members in pipeline
    order."""
    id: str
    name: str
    goal: str
    capabilities: list[str]
    overview_figure: str
    parts: list[Part]
    page_source: str = ""
    cross_links: list[str] = field(default_factory=list)


@dataclass
class FlagshipModel:
    stacks: list[FlagshipStack]


# ---- catalogue join sources -------------------------------------------------------------------------

_ROLE_DIRS = ("agent", "models-bridge", "product")


def _entry_slugs() -> "set[str]":
    """The join target for FS1 — the bare slug of every catalogue entry, read from the entry .md files on
    disk at check time. Entries live at `<role>/<family>/<slug>.md`; the bare slug is unique across the
    catalogue, so a part's `slug` resolves against this set with no ambiguity."""
    slugs: "set[str]" = set()
    for role in _ROLE_DIRS:
        root = os.path.join(_ROOT, role)
        if not os.path.isdir(root):
            continue
        for family in os.listdir(root):
            fam = os.path.join(root, family)
            if not os.path.isdir(fam):
                continue
            for name in os.listdir(fam):
                if name.endswith(".md"):
                    slugs.add(name[:-3])
    return slugs


def _gee_capabilities() -> "set[str]":
    """The valid `capability` set — the GEE capabilities named in the classification, read at check time."""
    if not os.path.isfile(_CLASSIFICATION):
        return set()
    data = json.load(open(_CLASSIFICATION, encoding="utf-8"))
    caps = data.get("gee_capabilities", [])
    return {c if isinstance(c, str) else c.get("name", "") for c in caps}


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model() -> FlagshipModel:
    """Build the model from the hand-authored declarations — the single derivation regen and the drift check
    share. Order is the authored order (pipeline order within a stack), so the artifact is deterministic."""
    decl = _load_declared()
    known = _entry_slugs()
    stacks: list[FlagshipStack] = []
    for s in decl.get("stacks", []):
        parts = [Part(
            slug=p["slug"], role=p.get("role", ""), failure=p.get("failure", ""),
            mechanism=p.get("mechanism", ""), seam=p.get("seam", ""),
            durability=p.get("durability", ""), resolves=p["slug"] in known,
        ) for p in s.get("parts", [])]
        stacks.append(FlagshipStack(
            id=s["id"], name=s["name"], goal=s.get("goal", ""),
            capabilities=list(s.get("capabilities", [])),
            overview_figure=s.get("overview_figure", ""),
            parts=parts, page_source=s.get("page_source", ""),
            cross_links=list(s.get("cross_links", [])),
        ))
    return FlagshipModel(stacks=stacks)


# ---- FS3 figure house-rules (per-figure, not the global scanners) -----------------------------------

_HEX_RE = re.compile(r'(?:fill|stroke)="(#[0-9a-fA-F]{3,8}|none)"')


def _figure_findings(figure_rel: str) -> "list[str]":
    """FS3 — run the figure-overflow sensor and the design-token palette on ONE figure (the stack's own),
    not the global scanners' whole-directory sweep. Returns audit strings; empty when the figure is clean.
    A missing figure is reported by FS2, not here."""
    out: "list[str]" = []
    path = os.path.join(_ROOT, figure_rel)
    if not os.path.isfile(path):
        return out
    try:
        import lint_figure_overflow as lfo  # noqa: E402 — sibling book-model lint
        for f in lfo.analyze(__import__("pathlib").Path(path), lfo.load_faces()):
            if f.verdict == "OVERFLOW":
                out.append(f"FS3 {os.path.basename(figure_rel)} label {f.text!r} OVERFLOWS its box "
                           f"(ratio {f.ratio:.2f})")
    except Exception as exc:  # pragma: no cover — the sensor is advisory; a parse hiccup must not mask FS1/2
        out.append(f"FS3 figure-overflow sensor could not read {figure_rel}: {exc}")
    try:
        import design_tokens as dtk  # noqa: E402 — sibling book-model tokens
        palette = {h.lower() for h in dtk.svg_palette()}
        text = open(path, encoding="utf-8").read()
        for hx in {m.lower() for m in _HEX_RE.findall(text)}:
            if hx != "none" and hx not in palette:
                out.append(f"FS3 {os.path.basename(figure_rel)} hex {hx!r} is not a design token "
                           f"(re-map to the nearest palette token)")
    except Exception as exc:  # pragma: no cover — advisory, same rationale
        out.append(f"FS3 design-token palette could not read {figure_rel}: {exc}")
    return out


# ---- invariants (FS1–FS5) ---------------------------------------------------------------------------

def structural_findings(model: "FlagshipModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants FS1–FS5. Deterministic. FS4 is a DEFERRED note while the model
    carries fewer than EXPECTED_STACKS records (the coverage claim is only meaningful once all seven are in).

    FS1 — join integrity: every `parts[].slug` resolves to a catalogue entry on disk.
    FS2 — page shape: non-empty goal; a `capability` in the GEE set; an overview_figure asset that EXISTS;
          at least MIN_PARTS parts, each with all six template fields non-empty; ids unique + kebab.
    FS3 — figure house-rules: the overview_figure passes the overflow sensor + the design-token palette.
    FS4 — coverage (deferred while under-populated): the union of part slugs should cover the strong
          compositions' members. Deferred to a note until the seventh stack lands.
    FS5 — freshness (optional): the stack's page source renders its part-set — the overview figure basename
          and every part slug appear in the page markdown.
    """
    if model is None:
        model = derive_model()
    findings: "list[str]" = []
    caps = _gee_capabilities()

    # FS1 — join integrity.
    for s in model.stacks:
        for p in s.parts:
            if not p.resolves:
                findings.append(f"FS1 stack {s.id!r} part {p.slug!r} resolves to no catalogue entry")

    # FS2 — page shape.
    seen: "set[str]" = set()
    for s in model.stacks:
        if s.id in seen:
            findings.append(f"FS2 duplicate stack id {s.id!r}")
        seen.add(s.id)
        if not all(part.isalnum() for part in s.id.split("-")) or s.id != s.id.lower():
            findings.append(f"FS2 stack id {s.id!r} is not kebab-case")
        if not s.goal.strip():
            findings.append(f"FS2 stack {s.id!r} has an empty goal line")
        if not s.capabilities:
            findings.append(f"FS2 stack {s.id!r} declares no capabilities (needs ≥ 1 GEE capability)")
        for cap in s.capabilities:
            if caps and cap not in caps:
                findings.append(f"FS2 stack {s.id!r} capability {cap!r} is not a GEE capability")
        if not s.overview_figure:
            findings.append(f"FS2 stack {s.id!r} declares no overview_figure")
        elif not os.path.isfile(os.path.join(_ROOT, s.overview_figure)):
            findings.append(f"FS2 stack {s.id!r} overview_figure {s.overview_figure!r} does not exist")
        if len(s.parts) < MIN_PARTS:
            findings.append(f"FS2 stack {s.id!r} has {len(s.parts)} part(s) — a stack needs ≥ {MIN_PARTS}")
        for p in s.parts:
            for f_name in PART_FIELDS:
                if not str(getattr(p, f_name)).strip():
                    findings.append(f"FS2 stack {s.id!r} part {p.slug!r} has an empty {f_name!r} field")

    # FS3 — figure house-rules, per stack figure.
    for s in model.stacks:
        if s.overview_figure:
            findings.extend(_figure_findings(s.overview_figure))

    # FS4 — coverage (deferred while under-populated). Only meaningful once all seven stacks are in; until
    # then it is an informational note, not a finding (surfaced by the CLI, not appended here).

    # FS5 — freshness (optional): the page source renders the model's part-set.
    for s in model.stacks:
        if not s.page_source:
            continue
        src = os.path.join(_ROOT, s.page_source)
        if not os.path.isfile(src):
            findings.append(f"FS5 stack {s.id!r} page_source {s.page_source!r} does not exist")
            continue
        page = open(src, encoding="utf-8").read()
        if s.overview_figure and os.path.basename(s.overview_figure) not in page:
            findings.append(f"FS5 stack {s.id!r} page does not reference its overview figure "
                            f"{os.path.basename(s.overview_figure)}")
        for p in s.parts:
            if p.slug not in page:
                findings.append(f"FS5 stack {s.id!r} page does not render part {p.slug!r} "
                                f"(model part-set drifted from the page)")
    return findings


#: FS4 author's documented moves — strong-composition members that are covered OUTSIDE the flagship
#: deep-dives, so their absence from any stack's parts is NOT a coverage gap. Keyed by the composition
#: name in catalogue-classification.json. The evidence-staircase composition is treated in the Validation
#: chapter, not a flagship stack; the worktree-lifecycle stack was retired (its mechanisms remain as
#: catalogue entries). Fleet observability is covered live in the observe → react loop. Reframe 260803.
_FS4_MOVED_COMPOSITIONS = frozenset({"The evidence staircase"})


def _l2_name_to_slug() -> "dict[str, str]":
    """Build the FS4 JOIN — L2-pattern NAME → catalogue entry SLUG — from the classification's
    `canonical_card` path per pattern. The compositions key their members by L2-pattern NAME; a stack's
    parts key by entry SLUG. This map is the join that lets FS4 compare the two (single source of truth:
    the classification file, read at check time — no snapshot). The `canonical_card` is a `<role>/<family>/
    <slug>` path (with or without a `.md` suffix); the bare slug is its basename."""
    out: "dict[str, str]" = {}
    if not os.path.isfile(_CLASSIFICATION):
        return out
    data = json.load(open(_CLASSIFICATION, encoding="utf-8"))
    for name, rec in data.get("L2_patterns", {}).items():
        card = rec.get("canonical_card", "") if isinstance(rec, dict) else ""
        if not card:
            continue
        base = os.path.basename(card)
        out[name] = base[:-3] if base.endswith(".md") else base
    return out


def _fs4_moved_members() -> "set[str]":
    """FS4 EXEMPTION SET — the L2-pattern names appearing in any moved composition. A member handled outside
    the flagship deep-dives (e.g. Staged Admission Gates, in the moved evidence-staircase) is exempt even
    where it ALSO appears in a non-moved composition, so it is not spuriously reported as an uncovered gap."""
    if not os.path.isfile(_CLASSIFICATION):
        return set()
    data = json.load(open(_CLASSIFICATION, encoding="utf-8"))
    moved: "set[str]" = set()
    for comp in data.get("compositions", []):
        if comp.get("name", "") in _FS4_MOVED_COMPOSITIONS:
            moved.update(comp.get("joins", []))
    return moved


def _strong_composition_members() -> "list[tuple[str, str, str]]":
    """FS4 coverage TARGET — every (composition-name, L2-pattern-name, entry-slug) triple across the
    classification's strong compositions, resolved through the L2→slug join, EXCLUDING members that belong
    to a moved composition (covered outside the flagship deep-dives). A composition entirely in
    `_FS4_MOVED_COMPOSITIONS` contributes nothing; a member shared with a moved composition is also dropped."""
    if not os.path.isfile(_CLASSIFICATION):
        return []
    data = json.load(open(_CLASSIFICATION, encoding="utf-8"))
    join = _l2_name_to_slug()
    moved_members = _fs4_moved_members()
    triples: "list[tuple[str, str, str]]" = []
    for comp in data.get("compositions", []):
        cname = comp.get("name", "")
        if cname in _FS4_MOVED_COMPOSITIONS:
            continue
        for l2 in comp.get("joins", []):
            if l2 in moved_members:
                continue
            triples.append((cname, l2, join.get(l2, "")))
    return triples


def coverage_note() -> str:
    """FS4 as a human-readable line. DEFERRED while the model carries fewer than EXPECTED_STACKS records;
    once all seven land it becomes REAL: it joins the classification's strong-composition members (by
    L2-pattern name) to catalogue slugs, subtracts the author's documented moves, and reports which members
    no flagship stack's parts cover. Informational; never a gate finding (FS4 does not enter the fail
    tally)."""
    model = derive_model()
    n = len(model.stacks)
    if n < EXPECTED_STACKS:
        return (f"FS4 coverage DEFERRED — {n}/{EXPECTED_STACKS} flagship stacks populated; the "
                f"composition-coverage claim is checked once all seven land.")
    covered = {p.slug for s in model.stacks for p in s.parts}
    target = _strong_composition_members()
    uncovered = [(c, l2, slug) for (c, l2, slug) in target if slug and slug not in covered]
    unresolved = [(c, l2) for (c, l2, slug) in target if not slug]
    parts = [f"FS4 coverage — {n} stacks populated; {len(covered)} distinct member entries; "
             f"{len(target) - len(uncovered) - len(unresolved)}/{len(target)} strong-composition members "
             f"(minus moved: {', '.join(sorted(_FS4_MOVED_COMPOSITIONS))}) land in a flagship stack."]
    for c, l2, slug in uncovered:
        parts.append(f"  · UNCOVERED — {l2!r} ({slug}) from {c!r} appears in no flagship stack's parts")
    for c, l2 in unresolved:
        parts.append(f"  · UNJOINED — {l2!r} from {c!r} resolves to no catalogue slug (classification "
                     f"canonical_card missing)")
    return "\n".join(parts)


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "FlagshipModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "stacks": len(model.stacks),
            "expected_stacks": EXPECTED_STACKS,
            "parts_total": sum(len(s.parts) for s in model.stacks),
            "parts_unresolved": sum(1 for s in model.stacks for p in s.parts if not p.resolves),
            "distinct_members": len({p.slug for s in model.stacks for p in s.parts}),
        },
        "taxonomy": {"part_fields": ["slug", *PART_FIELDS], "min_parts": MIN_PARTS,
                     "expected_stacks": EXPECTED_STACKS},
        "stacks": [asdict(s) for s in model.stacks],
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['stacks']}/{c['expected_stacks']} stacks; "
          f"{c['parts_total']} parts ({c['distinct_members']} distinct members, "
          f"{c['parts_unresolved']} unresolved)")
    findings = structural_findings()
    print(f"  {coverage_note()}")
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    else:
        print("  FS1–FS5 clean")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """FS-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    if any(stored.get(k) != fresh[k] for k in ("stacks", "_counts")):
        print("DRIFT: flagship-stack.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"flagship-stack.json is in sync ({fresh['_counts']['stacks']} stack(s), "
          f"{fresh['_counts']['parts_total']} parts)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _print_list() -> int:
    model = derive_model()
    print(f"== flagship stacks ({len(model.stacks)}/{EXPECTED_STACKS}) ==")
    for s in model.stacks:
        print(f"  {s.id}: {s.name}")
        print(f"    goal: {s.goal}")
        print(f"    capabilities: {' + '.join(s.capabilities)}  ·  {len(s.parts)} parts  "
              f"·  figure {s.overview_figure}")
    print(f"  {coverage_note()}")
    return 0


def _print_flagship(target: str) -> int:
    model = derive_model()
    match = next((s for s in model.stacks if s.id == target), None)
    if match is None:
        print(f"'{target}' is no flagship stack. Run `python3 book-models/flagship_stack_model.py list`.")
        return 1
    print(f"== {match.name} ({match.id}) ==")
    print(f"goal: {match.goal}")
    print(f"capabilities: {' + '.join(match.capabilities)}")
    print(f"figure: {match.overview_figure}")
    for i, p in enumerate(match.parts, 1):
        tag = "" if p.resolves else "  [UNRESOLVED slug]"
        print(f"\n{i}. {p.slug}{tag}")
        print(f"   role:       {p.role}")
        print(f"   failure:    {p.failure}")
        print(f"   mechanism:  {p.mechanism}")
        print(f"   seam:       {p.seam}")
        print(f"   durability: {p.durability}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "list":
        return _print_list()
    if cmd == "flagship":
        return _print_flagship(argv[2]) if len(argv) > 2 else _print_list()
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
