"""EMITTER — precompute the body font's per-glyph advance table to a committed JSON.

The figure-overflow sensor (`lint_figure_overflow.py`) estimates each SVG label's rendered
width from per-glyph advances. Reading those advances live from the TTFs would drag `fontTools`
into the lint's runtime — this catalogue stays stdlib-only / clone-and-run. So we extract the
advances ONCE, here, and commit the result to `glyph-advances.json`; the sensor reads that JSON
with plain `json`, no font library at runtime.

The advances are static per font file, so the table only changes when the bundled Source Sans 3
faces change. Re-run this emitter (and commit the refreshed JSON) if the fonts under
`book/fonts/SourceSans3/` are updated.

    python3 book-models/gen_glyph_advances.py            # regenerate glyph-advances.json

Needs `fontTools` (a build-time dependency of THIS emitter only — never of the sensor).
"""
from __future__ import annotations

import json
import pathlib

from fontTools.ttLib import TTFont

HERE = pathlib.Path(__file__).resolve().parent
FONT_DIR = HERE.parent / "book" / "fonts" / "SourceSans3"
OUT_JSON = HERE / "glyph-advances.json"

# (font-weight class, font-style) -> TTF. The figures mix weights and styles, and bold is
# materially wider than regular, so each face gets its own table.
FACE_FILES = {
    "normal|normal": "SourceSans3-Regular.ttf",
    "bold|normal": "SourceSans3-Bold.ttf",
    "normal|italic": "SourceSans3-It.ttf",
    "bold|italic": "SourceSans3-BoldIt.ttf",
}


def _face_table(fname: str) -> dict:
    font = TTFont(FONT_DIR / fname)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    advance_em: dict[str, float] = {}
    for codepoint, glyph_name in cmap.items():
        # Latin + common punctuation/symbols the labels use; skip control + far-plane glyphs.
        if codepoint < 0x20 or codepoint > 0x2FFF:
            continue
        adv, _lsb = hmtx[glyph_name]
        advance_em[chr(codepoint)] = round(adv / upm, 5)
    return {
        "font_file": fname,
        "units_per_em": upm,
        "space_em": advance_em.get(" ", 0.2),
        # Fallback advance for a glyph absent from the table — the lowercase 'n' width,
        # a representative mid-width letter (matches the sensor prototype's fallback).
        "fallback_em": advance_em.get("n", 0.5),
        "advance_em": dict(sorted(advance_em.items())),
    }


def build() -> dict:
    return {
        "_provenance": (
            "GENERATED by book-models/gen_glyph_advances.py from book/fonts/SourceSans3/*.ttf — "
            "do not hand-edit. Regen: python3 book-models/gen_glyph_advances.py"
        ),
        "_note": (
            "Per-glyph advance widths (em units) for the body font Source Sans 3, by weight|style "
            "face. The figure-overflow sensor reads this table so it needs no fontTools at runtime "
            "(stdlib-only / clone-and-run). Advances are static per font; regenerate only when the "
            "bundled faces change."
        ),
        "units": "advance-per-em",
        "faces": {key: _face_table(fname) for key, fname in FACE_FILES.items()},
    }


def main() -> int:
    payload = json.dumps(build(), ensure_ascii=False, indent=1) + "\n"
    OUT_JSON.write_text(payload, encoding="utf-8")
    n = sum(len(f["advance_em"]) for f in build()["faces"].values())
    print(f"wrote {OUT_JSON} — {len(FACE_FILES)} faces, {n} glyph advances total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
