"""The LEARNING-OUTCOMES view — a typed model of what a reader should be able to DO or KNOW after each
unit of the book, and which unit teaches which outcome. The book's 6th 4+1-style view (DESIGN §2.6).

Kruchten has no analogue: this is a book-specific PEDAGOGICAL view (the book is a textbook, so it is
modeled as one). Quality question: does every teaching unit — book, Part, chapter, and the sampled
sections — declare what a reader should be able to do after it, does that outcome map to a real unit, and
does the Part→chapter→section outcome tree decompose without gaps?

An OUTCOME is an ACTION VERB + OBJECT — "distinguish a constraint from a sensor," "size a transformation to
the model and the guarantee" — pinned to a Bloom cognitive level and to the outline unit that develops it.

THREE-WAY PROVENANCE — honest labeling is the load-bearing rule.  Every outcome carries a `provenance` tag
that says how honestly it reflects the prose AS WRITTEN:
  - `derived`         — grounded in what the unit ACTUALLY teaches, traceable to an anchor (a topic sentence
                        or heading). The "what the book teaches as written" set.
  - `declared`        — a real outcome the existing (sometimes thin) prose roughly supports, made explicit
                        by the author (e.g. a chapter outcome synthesized across its section titles).
  - `gap-recommended` — the outcome a MISSING or inadequately-delivered unit OUGHT to deliver; a
                        recommendation for content that does NOT yet exist. Never masqueraded as derived.
`derived` candidates are lifted mechanically by `_derive_section_candidates()` from verb-led topic sentences;
`declared` and `gap-recommended` outcomes are hand-authored in `outcomes_declared.json` with an `anchor`
(for declared, the grounding prose) or a gap note (for gap-recommended, why the unit falls short). The
declared + gap-recommended sets ARE the author's rearrange/fill worklist. The regen merges: a hand-authored
declaration wins on the units it names; a mechanically-derived candidate fills a section left silent.

NO NEW MARKDOWN SYMBOL.  Outcomes live in this model's `outcomes.json`, keyed by outline section ids — the
renderer stays uncoupled (DESIGN §2.6 "notation decision"). An inline `<!-- outcome: … -->` marker is
*proposed* in DESIGN §3.3 but deliberately NOT wired into the renderer's marker vocabulary here.

Run `python3 book-models/outcomes_model.py regenerate` to write the artifact; `... verify` to drift-check;
`... gaps` to list units with no outcome (the author's rearrange/fill worklist).
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import book_symbols as bs  # noqa: E402 — sibling helper; read-only symbol-extraction over book_ir
import outline_model as om  # noqa: E402 — the outline view is the unit tree outcomes map onto

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outcomes.json")
_DECLARED = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outcomes_declared.json")
_PROVENANCE = ("GENERATED by book-models/outcomes_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/outcomes_model.py regenerate`. Derived from the book (topic sentences) "
               "+ declared outcomes in book-models/outcomes_declared.json.")

# ---- the verb taxonomy ------------------------------------------------------------------------------
# A CLOSED set of teaching verbs, grouped by Bloom cognitive level (2001 revision). The set is tuned to
# THIS book's pedagogy — a governance / MBSE / AI-first-engineering textbook whose outcomes run from
# "recognize a mechanism" through "design a control." An outcome's verb MUST be in this set (checked as
# invariant U4), so the vocabulary stays uniform and the Bloom level is derivable from the verb alone.

BLOOM_VERBS: "dict[str, tuple[str, ...]]" = {
    # KNOW — recall / recognize a named thing exists.
    "know": ("recall", "recognize", "name", "list", "define", "identify"),
    # UNDERSTAND — explain it in your own words; tell two things apart.
    "understand": ("explain", "describe", "distinguish", "summarize", "interpret", "restate", "relate"),
    # APPLY — carry the move out on a new case.
    "apply": ("apply", "use", "compute", "write", "run", "route", "instantiate", "adopt"),
    # ANALYZE — take a situation apart; place it on an axis.
    "analyze": ("analyze", "classify", "map", "trace", "compare", "diagnose", "situate", "decompose"),
    # EVALUATE — judge; size a decision; choose among options.
    "evaluate": ("evaluate", "judge", "size", "critique", "justify", "choose", "weigh", "assess"),
    # CREATE — build a new artifact of the taught kind.
    "create": ("design", "construct", "author", "compose", "derive", "build", "model", "generate"),
}
_VERB_TO_BLOOM: "dict[str, str]" = {v: b for b, vs in BLOOM_VERBS.items() for v in vs}
_ALL_VERBS: frozenset = frozenset(_VERB_TO_BLOOM)

#: The four unit granularities the outcome tree decomposes through (book → Part → chapter → section).
GRANULARITIES = ("book", "part", "chapter", "section")

#: The three honesty tags an outcome carries — how faithfully it reflects the prose as written.
#:   derived         → the book teaches it as written (mechanically lifted or anchored to real prose).
#:   declared        → thin prose roughly supports it; the author makes it explicit.
#:   gap-recommended → the outcome a MISSING / inadequate unit ought to deliver (content not yet written).
PROVENANCE_TAGS = ("derived", "declared", "gap-recommended")


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Outcome:
    """One learning outcome: an action verb + object, pinned to a unit and a Bloom level.

    `unit_id` is the JOIN KEY into the outline's unit space:
      - granularity "section" → an outline `section_id`.
      - granularity "chapter" → an outline chapter `slug`.
      - granularity "part"    → `part-<N>`.
      - granularity "book"    → `book`.
    """
    outcome_id: str          # stable id: "<unit_id>::<verb>-<slug-of-object>"
    granularity: str         # book | part | chapter | section
    unit_id: str             # the outline unit this outcome belongs to (the join key)
    verb: str                # a teaching verb from BLOOM_VERBS
    obj: str                 # the object the verb acts on ("a constraint from a sensor")
    statement: str           # the full outcome sentence a reader reads
    bloom: str               # derived from the verb (know|understand|apply|analyze|evaluate|create)
    provenance: str          # derived | declared | gap-recommended (PROVENANCE_TAGS — honesty tag)
    anchor: "str | None" = None           # the grounding prose (topic sentence / heading) for a derived/declared outcome
    gap_note: "str | None" = None          # for gap-recommended: why the unit is missing/inadequate


@dataclass
class OutcomeModel:
    outcomes: list[Outcome]

    def by_unit(self) -> "dict[str, list[Outcome]]":
        d: "dict[str, list[Outcome]]" = {}
        for o in self.outcomes:
            d.setdefault(o.unit_id, []).append(o)
        return d


# ---- derivation: lift candidate outcomes from verb-led topic sentences ------------------------------

#: A topic sentence whose FIRST word is a teaching verb is a free candidate outcome: the section opens by
#: telling the reader to DO the taught thing. Kept HIGH-PRECISION on purpose (honesty over coverage): we
#: accept only an opener that is literally a taxonomy verb, plus a SHORT allow-list of trustworthy
#: inflections. We deliberately EXCLUDE navigational imperatives — "Start at the decision on the left",
#: "Start coarse and refine", "Read the stack as …" — because those instruct the READER's path through the
#: page, not a learning outcome. Lifting them would manufacture a garbled outcome masquerading as derived,
#: exactly the dishonesty the three-way provenance tags exist to prevent. When in doubt, do NOT derive —
#: leave the section a gap the author fills with a declaration.
_INFLECTION_LEMMA: "dict[str, str]" = {
    # opener form → taxonomy VERB (each RHS must be a member of some BLOOM_VERBS group).
    "measure": "compute",
}

#: Openers that LOOK like verbs but instruct navigation / reading, not a learning outcome — never derived.
_NAVIGATIONAL_OPENERS = frozenset({"start", "give", "read", "go", "look", "step", "slide", "turn"})


def _lemma_for_opener(word: str) -> "str | None":
    """Map a topic-sentence opening word to a taxonomy verb, or None if it is not a teaching verb (or is a
    navigational imperative we refuse to derive from)."""
    w = word.lower().strip(".,:;\"'*")
    if w in _NAVIGATIONAL_OPENERS:
        return None
    if w in _ALL_VERBS:
        return w
    return _INFLECTION_LEMMA.get(w)


def _derive_section_candidates() -> "list[Outcome]":
    """Lift a CANDIDATE section outcome from every section whose topic sentence opens on a teaching verb.
    A cheap, structural signal — the imperative opener IS a stated outcome ("Name both ends before you
    move." → apply: name both ends of a brownfield move). Declared outcomes override these per unit."""
    outline = om.derive_outline()
    out: "list[Outcome]" = []
    for _c, s in outline.sections():
        if not s.topic_sentence:
            continue
        first = s.topic_sentence.split()[0] if s.topic_sentence.split() else ""
        lemma = _lemma_for_opener(first)
        if lemma is None:
            continue
        obj = _trim_object(s.topic_sentence)
        out.append(_mk_outcome(
            granularity="section", unit_id=s.section_id, verb=lemma, obj=obj,
            statement=f"After this section, the reader can {lemma} {obj}.",
            provenance="derived", anchor=f"ts: {s.topic_sentence[:90]}"))
    return out


def _trim_object(sentence: str) -> str:
    """A coarse object phrase for a derived outcome — the topic sentence minus its opening verb, clipped to
    a readable length. This is a candidate the author refines into a declaration; it need not be perfect."""
    words = sentence.split()
    tail = " ".join(words[1:]).rstrip(".")
    return (tail[:70].rsplit(" ", 1)[0] + " …") if len(tail) > 72 else tail


# ---- declared outcomes: authored, keyed by outline unit ids -----------------------------------------

def _slug_object(obj: str) -> str:
    return bs.slugify(obj)[:40].strip("-") or "outcome"


def _mk_outcome(*, granularity: str, unit_id: str, verb: str, obj: str, statement: str,
                provenance: str, anchor: "str | None" = None,
                gap_note: "str | None" = None) -> Outcome:
    if verb not in _ALL_VERBS:
        raise ValueError(f"verb {verb!r} not in the outcome taxonomy (BLOOM_VERBS)")
    if provenance not in PROVENANCE_TAGS:
        raise ValueError(f"provenance {provenance!r} not in {PROVENANCE_TAGS}")
    return Outcome(
        outcome_id=f"{unit_id}::{verb}-{_slug_object(obj)}",
        granularity=granularity, unit_id=unit_id, verb=verb, obj=obj,
        statement=statement, bloom=_VERB_TO_BLOOM[verb], provenance=provenance,
        anchor=anchor, gap_note=gap_note)


def _load_declared() -> "list[dict]":
    """The authored outcome declarations — a flat list of
    {granularity, unit_id, verb, obj, statement?, provenance, anchor?, gap_note?}."""
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)["declarations"]


def _declared_outcomes() -> "list[Outcome]":
    """The hand-authored outcomes — `declared` (thin prose supports) and `gap-recommended` (content the unit
    ought to deliver but does not yet). NOTE: a hand-authored outcome may also be tagged `derived` when it is
    tightly anchored to a real heading/topic sentence — the tag reflects honesty, not who typed it."""
    out: "list[Outcome]" = []
    for d in _load_declared():
        verb, obj = d["verb"], d["obj"]
        statement = d.get("statement") or f"After this unit, the reader can {verb} {obj}."
        out.append(_mk_outcome(granularity=d["granularity"], unit_id=d["unit_id"], verb=verb, obj=obj,
                               statement=statement, provenance=d.get("provenance", "declared"),
                               anchor=d.get("anchor"), gap_note=d.get("gap_note")))
    return out


# ---- merge: declared wins per unit; derived fills the silence ---------------------------------------

def derive_model() -> OutcomeModel:
    """Build the full outcome model: declared outcomes, plus derived section candidates for every section a
    declaration does not already cover. The single derivation the regen and the drift check share."""
    declared = _declared_outcomes()
    declared_units = {o.unit_id for o in declared}
    derived = [o for o in _derive_section_candidates() if o.unit_id not in declared_units]
    # Stable order: by granularity tier, then unit_id, then verb — deterministic artifact.
    tier = {g: i for i, g in enumerate(GRANULARITIES)}
    both = declared + derived
    both.sort(key=lambda o: (tier[o.granularity], o.unit_id, o.verb, o.obj))
    return OutcomeModel(outcomes=both)


# ---- invariants (walked by the drift check in tests/book_models.py) ---------------------------------

def coverage_findings(model: OutcomeModel) -> "list[str]":
    """The coverage / drift invariants (U1–U5). Each finding is a GAP SIGNAL the author uses to rearrange
    content and fill pedagogy holes — this is the view's product, not just a lint.

    U1 — every outcome's unit_id resolves to a real outline unit (section id / chapter slug / part-N / book).
    U2 — every verb is in the taxonomy (BLOOM_VERBS); bloom equals the verb's level.
    U3 — every chapter has ≥1 outcome (a chapter with none is a pedagogy gap).
    U4 — every Part has ≥1 outcome (a Part with none is a pedagogy gap).
    U5 — the book has ≥1 book-level outcome.
    U6 — every outcome's provenance is a valid tag; a `derived`/`declared` outcome cites an anchor and a
         `gap-recommended` one cites a gap note (honest-labeling discipline).
    Section-level gaps are reported by `section_gap_findings` (informational, not a U-invariant, since not
    every section must carry its own outcome — the author decides which do)."""
    outline = om.derive_outline()
    section_ids = {s.section_id for _c, s in outline.sections()}
    chapter_slugs = {c.slug for c in outline.chapters}
    parts = {c.part for c in outline.chapters}

    findings: "list[str]" = []
    for o in model.outcomes:
        # U1 — unit resolves.
        if o.granularity == "section" and o.unit_id not in section_ids:
            findings.append(f"U1 outcome {o.outcome_id!r} maps to unknown section id {o.unit_id!r}")
        elif o.granularity == "chapter" and o.unit_id not in chapter_slugs:
            findings.append(f"U1 outcome {o.outcome_id!r} maps to unknown chapter slug {o.unit_id!r}")
        elif o.granularity == "part":
            n = o.unit_id.removeprefix("part-")
            if not (n.isdigit() and int(n) in parts):
                findings.append(f"U1 outcome {o.outcome_id!r} maps to unknown part {o.unit_id!r}")
        elif o.granularity == "book" and o.unit_id != "book":
            findings.append(f"U1 book outcome {o.outcome_id!r} has non-'book' unit_id {o.unit_id!r}")
        # U2 — verb + bloom consistency.
        if o.verb not in _ALL_VERBS:
            findings.append(f"U2 outcome {o.outcome_id!r} uses non-taxonomy verb {o.verb!r}")
        elif o.bloom != _VERB_TO_BLOOM[o.verb]:
            findings.append(f"U2 outcome {o.outcome_id!r} bloom {o.bloom!r} ≠ verb level "
                            f"{_VERB_TO_BLOOM[o.verb]!r}")
        # U6 — provenance honesty: valid tag + the right grounding for its tag.
        if o.provenance not in PROVENANCE_TAGS:
            findings.append(f"U6 outcome {o.outcome_id!r} has invalid provenance {o.provenance!r}")
        elif o.provenance in ("derived", "declared") and not o.anchor:
            findings.append(f"U6 outcome {o.outcome_id!r} is {o.provenance} but cites no anchor "
                            f"(a derived/declared outcome must name its grounding prose)")
        elif o.provenance == "gap-recommended" and not o.gap_note:
            findings.append(f"U6 outcome {o.outcome_id!r} is gap-recommended but cites no gap_note "
                            f"(a recommended outcome must name why the unit falls short)")

    covered = model.by_unit()
    # U3 — every chapter covered (directly, or via a section it owns).
    section_to_chapter = {s.section_id: c.slug for c in outline.chapters for s in c.sections}
    covered_chapters = {u for u in covered if u in chapter_slugs}
    covered_chapters |= {section_to_chapter[u] for u in covered if u in section_to_chapter}
    for c in outline.chapters:
        if c.part == 0:
            continue  # front/back matter (preface, acknowledgments) — not a taught chapter
        if c.slug not in covered_chapters:
            findings.append(f"U3 chapter {c.slug!r} (part {c.part}) has NO outcome — pedagogy gap")
    # U4 — every taught Part covered.
    covered_parts = {int(u.removeprefix("part-")) for u in covered if u.startswith("part-")}
    for p in sorted(parts):
        if p == 0:
            continue
        if p not in covered_parts:
            findings.append(f"U4 part {p} has NO part-level outcome — pedagogy gap")
    # U5 — the book has a book-level outcome.
    if "book" not in covered:
        findings.append("U5 the book has NO book-level outcome")
    return findings


def section_gap_findings(model: OutcomeModel) -> "list[str]":
    """INFORMATIONAL: sections with no outcome (direct or derived). The author's fill worklist — a section
    that teaches something but carries no outcome is a candidate for a declaration (or for merging away)."""
    outline = om.derive_outline()
    covered = set(model.by_unit())
    gaps: "list[str]" = []
    for c in outline.chapters:
        if c.part == 0:
            continue
        for s in c.sections:
            if s.section_id not in covered:
                ts = (s.topic_sentence or "(no topic sentence)")[:60]
                gaps.append(f"[{c.slug}] section {s.section_id!r} (L{s.level}) — no outcome | ts: {ts}")
    return gaps


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: OutcomeModel) -> dict:
    outline = om.derive_outline()
    n_sections = len(outline.sections())
    covered_sections = {o.unit_id for o in model.outcomes if o.granularity == "section"}
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "outcomes": len(model.outcomes),
            "by_provenance": {p: sum(1 for o in model.outcomes if o.provenance == p)
                              for p in PROVENANCE_TAGS},
            "by_granularity": {g: sum(1 for o in model.outcomes if o.granularity == g)
                               for g in GRANULARITIES},
            "by_bloom": {b: sum(1 for o in model.outcomes if o.bloom == b) for b in BLOOM_VERBS},
            "sections_total": n_sections,
            "sections_with_outcome": len(covered_sections),
        },
        "taxonomy": {b: list(vs) for b, vs in BLOOM_VERBS.items()},
        "outcomes": [asdict(o) for o in model.outcomes],
    }


def regenerate() -> int:
    model = derive_model()
    payload = to_jsonable(model)
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['outcomes']} outcomes "
          f"(by provenance {c['by_provenance']}); "
          f"by granularity {c['by_granularity']}; "
          f"{c['sections_with_outcome']}/{c['sections_total']} sections covered")
    write_digest(model)
    cov = coverage_findings(model)
    if cov:
        print(f"  {len(cov)} coverage finding(s) (audit-only — see tests/book_models.py):")
        for f in cov:
            print(f"    {f}")
    return 0


_DIGEST = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outcomes-draft.md")


def write_digest(model: OutcomeModel) -> None:
    """Emit a human-readable, reviewable digest of the actual outcome STATEMENTS, organized book → Part →
    chapter → section, each tagged with its provenance (derived | declared | gap-recommended) and anchor.
    This is the surface the author reviews — the honesty of the induction is the thing to get right."""
    outline = om.derive_outline()
    part_of_chapter = {c.slug: c.part for c in outline.chapters}
    chapters_in_part: "dict[int, list[str]]" = {}
    for c in outline.chapters:
        chapters_in_part.setdefault(c.part, []).append(c.slug)
    section_to_chapter = {s.section_id: c.slug for c in outline.chapters for s in c.sections}
    by_unit = model.by_unit()

    tag = {"derived": "DERIVED", "declared": "DECLARED", "gap-recommended": "GAP-REC"}
    lines: "list[str]" = [
        "<!-- GENERATED by book-models/outcomes_model.py — reviewable digest of the outcomes view.",
        "     Do not hand-edit; edit book-models/outcomes_declared.json and regenerate. -->",
        "# Learning outcomes — reviewable draft\n",
        "Every outcome is tagged by how honestly it reflects the prose **as written**:",
        "- **DERIVED** — grounded in what the unit actually teaches (traceable to its anchor).",
        "- **DECLARED** — a real outcome the existing (thin) prose roughly supports, made explicit.",
        "- **GAP-REC** — the outcome a *missing / inadequate* unit ought to deliver (content not yet written).\n",
        "The DECLARED + GAP-REC sets are the rearrange/fill worklist. The DERIVED set is what the book "
        "teaches today.\n",
    ]

    def emit(o: "Outcome", indent: str) -> None:
        note = f" — _anchor: {o.anchor}_" if o.anchor else ""
        if o.gap_note:
            note = f" — _gap: {o.gap_note}_"
        lines.append(f"{indent}- **[{tag[o.provenance]}]** ({o.bloom}) {o.statement}{note}")

    # Book level.
    lines.append("## Book\n")
    for o in by_unit.get("book", []):
        emit(o, "")
    lines.append("")

    for part in sorted(p for p in chapters_in_part if p != 0):
        lines.append(f"## Part {part}\n")
        for o in by_unit.get(f"part-{part}", []):
            emit(o, "")
        lines.append("")
        for slug in chapters_in_part[part]:
            lines.append(f"### {slug}\n")
            for o in by_unit.get(slug, []):
                emit(o, "")
            # Section-level outcomes under this chapter, in section order.
            for u in [s.section_id for c in outline.chapters if c.slug == slug for s in c.sections]:
                for o in by_unit.get(u, []):
                    emit(o, "  ")
            lines.append("")

    with open(_DIGEST, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
    print(f"wrote {os.path.relpath(_DIGEST)} — reviewable outcome digest")


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """Drift check as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable(derive_model())
    if stored.get("outcomes") != fresh["outcomes"] or stored.get("_counts") != fresh["_counts"]:
        print("DRIFT: outcomes.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"outcomes.json is in sync ({fresh['_counts']['outcomes']} outcomes)")
    return 0


def gaps() -> int:
    """List the pedagogy gaps — chapters/parts with no outcome (U3/U4) and sections with none. The author's
    rearrange/fill worklist."""
    model = derive_model()
    cov = coverage_findings(model)
    sec = section_gap_findings(model)
    print(f"UNIT gaps (U1–U5): {len(cov)}")
    for f in cov:
        print(f"  {f}")
    print(f"\nSECTION gaps (informational): {len(sec)}")
    for f in sec:
        print(f"  {f}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "gaps":
        return gaps()
    print(f"usage: {argv[0]} [regenerate|verify|gaps]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
