"""The OUTLINE view — a typed model of the book's heading tree, each section carrying its stable id and
topic sentence. The proof-of-concept 4+1 view for the book (DESIGN §2.1).

Kruchten analogue: the Development view — how the source is organized. Quality question: is the heading
tree complete and coherent, every section down to sub-subsection level accounted for in the right nesting
order, each carrying a topic sentence that states its point?

DERIVED, NEVER SNAPSHOTTED.  `derive_outline()` re-induces the whole model from the book on every call via
the thin `book_symbols` helper over `book_ir` — there is no hand-authored source of truth to drift. The
JSON artifact (`outline.json`) is a *materialization* of that derivation, carrying a provenance header; the
drift check (`tests/book_models.py`) asserts the on-disk artifact equals a fresh derivation, so a hand-edit
or a stale regen is the finding. This is the `model-from-code` direction (the book is the code).

Run `python3 book-models/outline_model.py regenerate` to write the artifact; `... verify` to check it.
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import book_symbols as bs  # noqa: E402 — sibling helper; the read-only symbol-extraction over book_ir

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outline.json")
#: A valid canonical-point slug — lowercase alphanumerics joined by single hyphens (the O5 well-formedness
#: check). The join key the reverse index inverts, so it must be clean.
_KEBAB_SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_PROVENANCE = ("GENERATED by book-models/outline_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/outline_model.py regenerate`. Derived from the book via book_ir.")


@dataclass
class ParagraphPoint:
    """One induced canonical point under a section — derived from a `<!-- point: slug | text -->` decorator.
    The paragraph-granularity deepening of the outline (DESIGN §9): a drained section carries these; an
    un-drained section carries none and falls back to its topic sentence."""
    slug: str
    text: str
    block_index: int


@dataclass
class Section:
    """One heading (H2–H4) with its stable id, visible text, and the topic sentence that follows it. A
    DRAINED section also carries its paragraph `points` (from the `<!-- point: … -->` decorators); an
    un-drained one carries an empty list, preserving the section-level behavior for Parts not yet drained."""
    section_id: str
    level: int
    heading_text: str
    topic_sentence: "str | None"
    id_source: str  # "explicit" ({#slug} anchor) | "derived" (slug of heading text)
    block_index: int
    points: list[ParagraphPoint] = field(default_factory=list)


@dataclass
class OutlineChapter:
    slug: str
    part: int
    sections: list[Section] = field(default_factory=list)
    #: Canonical points that head a paragraph BEFORE the chapter's first heading (a chapter opener). Kept
    #: distinct from section points since they belong to no section. Empty for an un-drained chapter.
    preamble_points: list[ParagraphPoint] = field(default_factory=list)


@dataclass
class Outline:
    chapters: list[OutlineChapter]

    def sections(self) -> "list[tuple[OutlineChapter, Section]]":
        return [(c, s) for c in self.chapters for s in c.sections]


def derive_outline(include_appendices: bool = False) -> Outline:
    """Re-induce the outline from the book — the single derivation both the regen and the drift check use.
    MODEL-FROM-DECORATOR: a drained section's paragraph `points` derive from its `<!-- point: … -->`
    decorators (via `book_symbols`); an un-drained section keeps its empty points list and its topic
    sentence, so Parts not yet drained are unaffected."""
    by_chapter: dict[str, OutlineChapter] = {}
    order: list[str] = []
    for r in bs.heading_rows(include_appendices=include_appendices):
        if r.chapter_slug not in by_chapter:
            by_chapter[r.chapter_slug] = OutlineChapter(slug=r.chapter_slug, part=r.part)
            order.append(r.chapter_slug)
        by_chapter[r.chapter_slug].sections.append(Section(
            section_id=r.section_id, level=r.level, heading_text=r.heading_text,
            topic_sentence=r.topic_sentence, id_source=r.id_source, block_index=r.block_index,
            points=[ParagraphPoint(slug=p.slug, text=p.text, block_index=p.block_index) for p in r.points],
        ))
    # Attach chapter-opener points (a decorator before the chapter's first heading) at chapter scope.
    for slug, pts in bs.chapter_preamble_points(include_appendices=include_appendices).items():
        if slug in by_chapter:
            by_chapter[slug].preamble_points = [
                ParagraphPoint(slug=p.slug, text=p.text, block_index=p.block_index) for p in pts]
    return Outline(chapters=[by_chapter[s] for s in order])


# ---- invariants (checked by the drift check in tests/book_models.py) --------------------------------

def invariant_findings(outline: Outline) -> list[str]:
    """Walk the outline's four invariants and return a finding per violation (empty ⇒ clean).

    O2 — every section has a topic sentence (a heading followed by a float/list/code with no paragraph).
    O3 — section ids are unique per chapter (a collision breaks the outline's join key).
    O4 — heading nesting is well-formed (no H2→H4 jump skipping H3 — an outline hole).
    O5 — every canonical-point slug is a valid kebab slug (lowercase alnum + hyphens); a malformed slug is a
         decorator-authoring finding (the join key the reverse index inverts must be well-formed).

    O1 (the model equals a fresh derivation) is the drift check itself, not walked here — it compares the
    stored artifact against `derive_outline()` and lives in tests/book_models.py. Point-slug DUPLICATES /
    MALFORMED decorators are reported by the reverse index's `point_findings` (the drift substrate), not
    re-reported here — O5 is only the local slug-shape check.
    """
    findings: list[str] = []
    for c in outline.chapters:
        seen: dict[str, int] = {}
        prev_level = 1  # the H1 chapter title
        for p in c.preamble_points:
            if not _KEBAB_SLUG.match(p.slug):
                findings.append(f"O5 [{c.slug}] preamble point slug {p.slug!r} is not a valid kebab slug")
        for s in c.sections:
            if s.topic_sentence is None:
                findings.append(f"O2 [{c.slug}] section {s.section_id!r} (L{s.level} {s.heading_text!r}) "
                                f"has no topic sentence — opens on a non-paragraph block")
            if s.section_id in seen:
                findings.append(f"O3 [{c.slug}] duplicate section id {s.section_id!r} "
                                f"(blocks {seen[s.section_id]} and {s.block_index})")
            seen[s.section_id] = s.block_index
            if s.level > prev_level + 1:
                findings.append(f"O4 [{c.slug}] heading {s.heading_text!r} jumps L{prev_level}→L{s.level} "
                                f"(skips a level — outline hole)")
            for p in s.points:
                if not _KEBAB_SLUG.match(p.slug):
                    findings.append(f"O5 [{c.slug}] section {s.section_id!r} point slug {p.slug!r} is not a "
                                    f"valid kebab slug")
            prev_level = s.level
    return findings


def to_jsonable(outline: Outline) -> dict:
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "chapters": len(outline.chapters),
            "sections": sum(len(c.sections) for c in outline.chapters),
            "explicit_ids": sum(1 for _, s in outline.sections() if s.id_source == "explicit"),
            "derived_ids": sum(1 for _, s in outline.sections() if s.id_source == "derived"),
            "missing_topic_sentence": sum(1 for _, s in outline.sections() if s.topic_sentence is None),
            # Drain progress: sections that carry ≥1 canonical point, and total points (section + preamble).
            "sections_drained": sum(1 for _, s in outline.sections() if s.points),
            "paragraph_points": (sum(len(s.points) for _, s in outline.sections())
                                 + sum(len(c.preamble_points) for c in outline.chapters)),
        },
        "chapters": [asdict(c) for c in outline.chapters],
    }


def regenerate() -> int:
    outline = derive_outline()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(to_jsonable(outline), fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    counts = to_jsonable(outline)["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {counts['sections']} sections in "
          f"{counts['chapters']} chapters ({counts['explicit_ids']} explicit ids, "
          f"{counts['derived_ids']} derived; {counts['missing_topic_sentence']} without a topic sentence)")
    findings = invariant_findings(outline)
    if findings:
        print(f"  {len(findings)} invariant finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """Drift check as a CLI: assert the on-disk artifact equals a fresh derivation (O1)."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable(derive_outline())
    # Compare the model content (chapters), not the provenance string.
    if stored.get("chapters") != fresh["chapters"] or stored.get("_counts") != fresh["_counts"]:
        print("DRIFT: outline.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"outline.json is in sync ({fresh['_counts']['sections']} sections)")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    print(f"usage: {argv[0]} [regenerate|verify]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
