"""The REVERSE INDEX — a DERIVED projection that inverts every built view's forward references into
`{md symbol → [view elements that depend on it]}`. The drift layer's substrate (DESIGN §4).

WHY IT EXISTS.  The view-models (`outline`, `outcomes`) point FORWARD at md symbols: an outline section
rides a heading anchor / section id; an outcome names the units it teaches (a section id / chapter slug /
part-N / book) and cites a concept-or-heading anchor. Held that way, the question "if I edit section X,
which view elements break?" needs an O(views·elements) re-scan every time. The reverse index inverts the
forward edges ONCE, so the answer is one dict lookup — and the same inverted map is what turns the
structural drift audit into a single walk (does every symbol a view points at still exist in the source?).

DERIVED, NEVER HAND-AUTHORED.  `build_index()` re-inverts the views from the current source on every call.
There is no hand-authored source of truth, so the index itself cannot drift — a stale `reverse_index.json`
is caught by `verify()` (the on-disk artifact must equal a fresh inversion). The artifact carries a
provenance header and is TRACKED (diffable in PRs), mirroring `outline.json` / `outcomes.json`.

TWO SYMBOL ROLES.  A symbol appears in two ways, kept distinct so drift is precise:
  - DEFINED in the source  — the symbol universe: every section id / heading anchor / concept slug / float
    label / ref key / chapter slug / part that the book actually contains. Enumerated from `book_ir` +
    the outline view. A view reference to a symbol NOT in this set is a STRUCTURAL-DRIFT finding (dangling).
  - DEPENDED-ON by a view   — the inverted edge: which view elements point at this symbol. This is the
    reverse index proper; `deps <symbol>` reads it.

Run `python3 book-models/reverse_index.py regenerate` to write the artifact; `... verify` to drift-check;
`... deps <symbol>` to answer "edit this symbol → which view elements break?".
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import book_symbols as bs  # noqa: E402 — read-only symbol-extraction over book_ir
import outcomes_model as ocm  # noqa: E402 — the outcomes view (built) — a source of forward references
import outline_model as om  # noqa: E402 — the outline view (built) — a source of forward references

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reverse_index.json")
_PROVENANCE = ("GENERATED by book-models/reverse_index.py — do not hand-edit; regenerate with "
               "`python3 book-models/reverse_index.py regenerate`. A DERIVED inversion of every built "
               "view's forward references into {md symbol -> [dependent view elements]}; re-derived from "
               "the book (via book_ir + the view-models) each run, so it cannot itself drift.")

#: The `index-def: slug` / `index-example: slug` grammar — a concept anchor's slug lives in the directive's
#: raw comment. Parsed here (the anchor slug is not yet a first-class book_ir field — DESIGN §6.2).
_CONCEPT_DIRECTIVE = re.compile(r"^<!--\s*(index-def|index-example)\s*:\s*([a-z0-9-]+)\s*-->$", re.I)

#: The md symbol kinds the reverse index tracks. Each names a DIFFERENT source construct an edit can touch;
#: keeping them typed (not one flat string set) lets a `deps` answer say WHAT kind of symbol you edited and
#: lets the universe-membership drift check reason per-kind.
SYMBOL_KINDS = ("section-id", "concept", "label", "ref", "chapter", "part", "book")


# ---- the symbol universe: what the source actually DEFINES -------------------------------------------

@dataclass
class SymbolUniverse:
    """Every md symbol the book currently defines, grouped by kind. The resolve-target set the structural
    drift audit checks a view reference against. Derived fresh from `book_ir` + the outline view."""
    section_ids: "set[str]" = field(default_factory=set)   # outline section ids (explicit {#slug} or derived)
    concepts: "set[str]" = field(default_factory=set)      # <!-- index-def / index-example: slug -->
    labels: "set[str]" = field(default_factory=set)        # <!-- label: key --> float labels
    refs: "set[str]" = field(default_factory=set)          # [ref:key] keys that appear in prose
    chapters: "set[str]" = field(default_factory=set)      # chapter slugs
    parts: "set[int]" = field(default_factory=set)         # part numbers

    def resolves(self, symbol: str, kind: str) -> bool:
        """True when `symbol` is a real DEFINED symbol of the given `kind`. `book` and `part-<N>` are the
        two synthetic unit kinds the outcomes view uses; the rest name concrete source constructs."""
        if kind == "book":
            return symbol == "book"
        if kind == "part":
            n = symbol.removeprefix("part-")
            return n.isdigit() and int(n) in self.parts
        return symbol in {
            "section-id": self.section_ids, "concept": self.concepts, "label": self.labels,
            "ref": self.refs, "chapter": self.chapters,
        }.get(kind, set())

    def unit_kind(self, unit_id: str) -> str:
        """Classify an OUTCOME unit id (book | part-N | chapter slug | section id) to its symbol kind — the
        kind an outcome's primary/secondary reference resolves against. Matches the outcomes view's own
        `_unit_resolves` granularity order (book, part, chapter, then section)."""
        if unit_id == "book":
            return "book"
        if unit_id.startswith("part-") and unit_id.removeprefix("part-").isdigit():
            return "part"
        if unit_id in self.chapters:
            return "chapter"
        return "section-id"


def derive_universe() -> SymbolUniverse:
    """Enumerate every symbol the book DEFINES today. Section ids + chapters + parts come from the outline
    view (one structural source, no parallel parse); concepts / labels / refs come from `book_ir`."""
    doc = bs.book_ir.parse_book()
    u = SymbolUniverse()
    outline = om.derive_outline()
    for c in outline.chapters:
        u.chapters.add(c.slug)
        u.parts.add(c.part)
        for s in c.sections:
            u.section_ids.add(s.section_id)
    for c in doc.chapters:
        for b in c.blocks:
            m = _CONCEPT_DIRECTIVE.match(b.raw.strip()) if b.kind is bs.book_ir.BlockKind.DIRECTIVE else None
            if m:
                u.concepts.add(m.group(2))
    u.labels.update(doc.labels())
    u.refs.update(r.key for r in doc.refs())
    return u


# ---- the inverted edges: which view elements DEPEND on each symbol -----------------------------------

@dataclass
class Dependent:
    """One view element that points at a symbol — the reverse edge. `view` names which view (`outline` /
    `outcomes`); `element` is that view's stable element id (a section id, an outcome id); `role` says HOW
    the element uses the symbol (a section that IS this id; an outcome's `primary` / `secondary` unit; an
    outcome's cited `anchor`), so a `deps` answer explains the nature of each break, not just the count."""
    view: str
    element: str
    role: str


def _add(index: "dict[str, dict]", symbol: str, kind: str, dep: Dependent) -> None:
    slot = index.setdefault(symbol, {"kind": kind, "dependents": []})
    # A symbol keeps ONE kind; if two views disagree on a symbol's kind that is itself a signal, but in
    # practice the kind is a property of the symbol, not the referrer — keep the first, they agree.
    slot["dependents"].append(asdict(dep))


def build_index() -> "dict[str, dict]":
    """Invert every built view's forward references into `{symbol -> {kind, dependents:[Dependent]}}`.

    Forward edges inverted, per built view:
      - OUTLINE — every section RIDES a `section-id` (its heading anchor or derived id). Editing that
        heading's anchor moves the section's id, so the section depends on the symbol `section-id`.
      - OUTCOMES — every outcome names a `primary_unit` and any `secondary_units` (each a section id /
        chapter slug / part-N / book), and cites an `anchor` string. The unit references are the joins the
        coverage check walks; the anchor is the grounding prose an edit can invalidate. When an anchor
        string contains a concept/heading token we record the tokenized dependency too (best-effort: an
        `anchor` is prose, so we only invert the machine-checkable unit references as hard edges and record
        the anchor text as a soft `anchor` dependency keyed by the primary unit's symbol).
    """
    index: "dict[str, dict]" = {}
    universe = derive_universe()

    # OUTLINE: section rides its own section id.
    outline = om.derive_outline()
    for c in outline.chapters:
        for s in c.sections:
            _add(index, s.section_id, "section-id",
                 Dependent(view="outline", element=f"{c.slug}::{s.section_id}", role="section-anchor"))

    # OUTCOMES: primary + secondary units are hard join edges; the anchor is a soft grounding edge.
    model = ocm.derive_model()
    for o in model.outcomes:
        _add(index, o.primary_unit, universe.unit_kind(o.primary_unit),
             Dependent(view="outcomes", element=o.outcome_id, role="primary-unit"))
        for u in o.secondary_units:
            _add(index, u, universe.unit_kind(u),
                 Dependent(view="outcomes", element=o.outcome_id, role="secondary-unit"))

    # Stable order: sort dependents within each symbol for a deterministic artifact.
    for slot in index.values():
        slot["dependents"].sort(key=lambda d: (d["view"], d["role"], d["element"]))
    return index


# ---- structural drift: a view reference to a symbol the source no longer DEFINES --------------------

def structural_findings() -> "list[str]":
    """Every view->md reference re-resolved against the CURRENT source. A dangling reference — a section id
    / chapter / part / concept / label a view points at that the book no longer defines — is a finding.
    The reverse index makes this a single walk over the inverted edges. (STRUCTURAL half of the two-kind
    drift split — deterministic, a lint.)"""
    universe = derive_universe()
    index = build_index()
    findings: "list[str]" = []
    for symbol, slot in sorted(index.items()):
        kind = slot["kind"]
        if not universe.resolves(symbol, kind):
            dep_summary = ", ".join(f"{d['view']}:{d['element']}({d['role']})" for d in slot["dependents"])
            findings.append(f"DANGLING {kind} {symbol!r} — referenced by {len(slot['dependents'])} view "
                            f"element(s) but the book no longer defines it: {dep_summary}")
    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(index: "dict[str, dict] | None" = None) -> dict:
    if index is None:
        index = build_index()
    universe = derive_universe()
    by_kind: "dict[str, int]" = {}
    for slot in index.values():
        by_kind[slot["kind"]] = by_kind.get(slot["kind"], 0) + 1
    total_edges = sum(len(slot["dependents"]) for slot in index.values())
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "symbols_depended_on": len(index),
            "reverse_edges": total_edges,
            "by_symbol_kind": dict(sorted(by_kind.items())),
            "universe": {
                "section_ids": len(universe.section_ids), "concepts": len(universe.concepts),
                "labels": len(universe.labels), "refs": len(universe.refs),
                "chapters": len(universe.chapters), "parts": len(universe.parts),
            },
        },
        # symbol -> {kind, dependents:[{view, element, role}]}, keys sorted for a stable diff.
        "index": {k: index[k] for k in sorted(index)},
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['symbols_depended_on']} symbols depended on by "
          f"{c['reverse_edges']} reverse edge(s); by kind {c['by_symbol_kind']}")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural-drift finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """FRESHNESS drift check as a CLI: assert the on-disk artifact equals a fresh inversion. A stale
    artifact (a view edited, the index not regenerated) is the finding. (FRESHNESS half of the split.)"""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    if stored.get("index") != fresh["index"] or stored.get("_counts") != fresh["_counts"]:
        print("DRIFT: reverse_index.json disagrees with a fresh inversion — regenerate")
        return 1
    print(f"reverse_index.json is in sync ({fresh['_counts']['symbols_depended_on']} symbols)")
    return 0


def deps(symbol: str) -> int:
    """Answer "edit this symbol -> which view elements break?" — the inverted lookup. Prints every view
    element that depends on `symbol`, with its role, and whether the symbol currently resolves in the
    source (a non-resolving symbol is itself a dangling / structural-drift signal)."""
    index = build_index()
    universe = derive_universe()
    slot = index.get(symbol)
    if slot is None:
        # Not depended on by any view. Say whether it even exists in the source, so the caller can tell
        # "typo / wrong symbol" from "real symbol, but no view rides it (safe to edit)".
        defined = any(universe.resolves(symbol, k) for k in SYMBOL_KINDS)
        where = "IS defined in the source but no built view depends on it (safe to edit)" if defined \
            else "is NOT a defined symbol in the source (typo, or a symbol no view tracks)"
        print(f"{symbol!r}: no dependents — {where}")
        return 0
    kind = slot["kind"]
    resolves = universe.resolves(symbol, kind)
    flag = "" if resolves else "  ⚠ DANGLING — the source no longer defines this symbol"
    print(f"{symbol!r} ({kind}){flag}")
    print(f"  {len(slot['dependents'])} view element(s) depend on it:")
    for d in slot["dependents"]:
        print(f"    - {d['view']}: {d['element']}  [{d['role']}]")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "deps":
        if len(argv) < 3:
            print(f"usage: {argv[0]} deps <symbol>")
            return 2
        return deps(argv[2])
    print(f"usage: {argv[0]} [regenerate|verify|deps <symbol>]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
